[{"title":"BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neTabControl.MinorVersion.htm"}
,{"title":"neTabControl","href":"neTabControl.htm"}
,{"title":"neTabControl.THintStyle","href":"neTabControl.THintStyle.htm"}
,{"title":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"neTabControl.TneTabItem","href":"neTabControl.TneTabItem.htm"}
,{"title":"neTabControl.TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"neTabControl.TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
,{"title":"NETabControlPackage","href":"NETabControlPackage.htm"}
,{"title":"Register","href":"neTabControl.Register.htm"}
,{"title":"ResizeBitmap(TBitmap,Integer,Integer)","href":"neTabControl.ResizeBitmap.htm"}
,{"title":"THintStyle","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.None","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.ShowPreview","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.ShowTitle","href":"neTabControl.THintStyle.htm"}
,{"title":"TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"TneTabControl.AddTab(string,TFrame)","href":"neTabControl.TneTabControl.AddTab(string%2CTFrame).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.AddTab(string%2CTneTabItem%2CTFrame).htm"}
,{"title":"TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"TneTabControl.CloseTabLabel","href":"neTabControl.TneTabControl.CloseTabLabel.htm"}
,{"title":"TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"TneTabControl.DeleteTab(string)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
,{"title":"TneTabControl.FindTabOrderFromTag(string)","href":"neTabControl.TneTabControl.FindTabOrderFromTag.htm"}
,{"title":"TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"TneTabControl.GetTabsTags","href":"neTabControl.TneTabControl.GetTabsTags.htm"}
,{"title":"TneTabControl.GetTabsText","href":"neTabControl.TneTabControl.GetTabsText.htm"}
,{"title":"TneTabControl.HintStyle","href":"neTabControl.TneTabControl.HintStyle.htm"}
,{"title":"TneTabControl.InsertTab(string,Integer,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTFrame).htm"}
,{"title":"TneTabControl.InsertTab(string,Integer,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTneTabItem%2CTFrame).htm"}
,{"title":"TneTabControl.MaxTabWidth","href":"neTabControl.TneTabControl.MaxTabWidth.htm"}
,{"title":"TneTabControl.OnAfterDelete","href":"neTabControl.TneTabControl.OnAfterDelete.htm"}
,{"title":"TneTabControl.OnBeforeDelete","href":"neTabControl.TneTabControl.OnBeforeDelete.htm"}
,{"title":"TneTabControl.PopupAfterDefault","href":"neTabControl.TneTabControl.PopupAfterDefault.htm"}
,{"title":"TneTabControl.PopupBeforeDefault","href":"neTabControl.TneTabControl.PopupBeforeDefault.htm"}
,{"title":"TneTabControl.SetActiveTab(string)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
,{"title":"TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"TneTabItem","href":"neTabControl.TneTabItem.htm"}
,{"title":"TneTabItem.ApplyStyle","href":"neTabControl.TneTabItem.ApplyStyle.htm"}
,{"title":"TneTabItem.CanClose","href":"neTabControl.TneTabItem.CanClose.htm"}
,{"title":"TneTabItem.CloseImageHover","href":"neTabControl.TneTabItem.CloseImageHover.htm"}
,{"title":"TneTabItem.CloseImageNormal","href":"neTabControl.TneTabItem.CloseImageNormal.htm"}
,{"title":"TneTabItem.CloseImagePressed","href":"neTabControl.TneTabItem.CloseImagePressed.htm"}
,{"title":"TneTabItem.Create(TComponent)","href":"neTabControl.TneTabItem.Create.htm"}
,{"title":"TneTabItem.Deleted","href":"neTabControl.TneTabItem.Deleted.htm"}
,{"title":"TneTabItem.Icon","href":"neTabControl.TneTabItem.Icon.htm"}
,{"title":"TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseClick.htm"}
,{"title":"TneTabItem.ShowIcon","href":"neTabControl.TneTabItem.ShowIcon.htm"}
,{"title":"TneTabItem.Version","href":"neTabControl.TneTabItem.Version.htm"}
,{"title":"TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
]