[{"title":"BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"FindParentForm(TFmxObject)","href":"neTabControl.FindParentForm.htm"}
,{"title":"FindParentNeTabItem(TFMXObject)","href":"neTabControl.FindParentNeTabItem.htm"}
,{"title":"MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neTabControl.MinorVersion.htm"}
,{"title":"neTabControl","href":"neTabControl.htm"}
,{"title":"neTabControl.TExportElements","href":"neTabControl.TExportElements.htm"}
,{"title":"neTabControl.TExportElementsSet","href":"neTabControl.TExportElementsSet.htm"}
,{"title":"neTabControl.THintPanel","href":"neTabControl.THintPanel.htm"}
,{"title":"neTabControl.THintStyle","href":"neTabControl.THintStyle.htm"}
,{"title":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"neTabControl.TneTabItem","href":"neTabControl.TneTabItem.htm"}
,{"title":"neTabControl.TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"neTabControl.TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
,{"title":"neTabControl.TSetOfString","href":"neTabControl.TSetOfString.htm"}
,{"title":"neTabControlPackage","href":"neTabControlPackage.htm"}
,{"title":"Register","href":"neTabControl.Register.htm"}
,{"title":"ResizeBitmap(TBitmap,Integer,Integer)","href":"neTabControl.ResizeBitmap.htm"}
,{"title":"TExportElements","href":"neTabControl.TExportElements.htm"}
,{"title":"TExportElements.ExportIdentifier","href":"neTabControl.TExportElements.htm"}
,{"title":"TExportElements.ExportTagInt","href":"neTabControl.TExportElements.htm"}
,{"title":"TExportElements.ExportTagVariant","href":"neTabControl.TExportElements.htm"}
,{"title":"TExportElementsSet","href":"neTabControl.TExportElementsSet.htm"}
,{"title":"THintPanel","href":"neTabControl.THintPanel.htm"}
,{"title":"THintPanel.ApplyStyle","href":"neTabControl.THintPanel.ApplyStyle.htm"}
,{"title":"THintPanel.fHintStyle","href":"neTabControl.THintPanel.fHintStyle.htm"}
,{"title":"THintPanel.fHintText","href":"neTabControl.THintPanel.fHintText.htm"}
,{"title":"THintPanel.HintStyle","href":"neTabControl.THintPanel.HintStyle.htm"}
,{"title":"THintPanel.HintText","href":"neTabControl.THintPanel.HintText.htm"}
,{"title":"THintPanel.SetHintStyle(THintStyle)","href":"neTabControl.THintPanel.SetHintStyle.htm"}
,{"title":"THintPanel.SetHintText(string)","href":"neTabControl.THintPanel.SetHintText.htm"}
,{"title":"THintStyle","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.None","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.ShowPreview","href":"neTabControl.THintStyle.htm"}
,{"title":"THintStyle.ShowTitle","href":"neTabControl.THintStyle.htm"}
,{"title":"TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"TneTabControl.AddTab(string,TFrame)","href":"neTabControl.TneTabControl.AddTab(string%2CTFrame).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.AddTab(string%2CTneTabItem%2CTFrame).htm"}
,{"title":"TneTabControl.AddTab(string,TTabItem,TFrame)","href":"neTabControl.TneTabControl.AddTab(string%2CTTabItem%2CTFrame).htm"}
,{"title":"TneTabControl.CleanUpTabs","href":"neTabControl.TneTabControl.CleanUpTabs.htm"}
,{"title":"TneTabControl.CloseAllOtherTabsLabel","href":"neTabControl.TneTabControl.CloseAllOtherTabsLabel.htm"}
,{"title":"TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"TneTabControl.CloseTabLabel","href":"neTabControl.TneTabControl.CloseTabLabel.htm"}
,{"title":"TneTabControl.CloseTabOnDoubleClick","href":"neTabControl.TneTabControl.CloseTabOnDoubleClick.htm"}
,{"title":"TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"TneTabControl.DblClick","href":"neTabControl.TneTabControl.DblClick.htm"}
,{"title":"TneTabControl.DeleteAllTabs(boolean)","href":"neTabControl.TneTabControl.DeleteAllTabs.htm"}
,{"title":"TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
,{"title":"TneTabControl.DisablePopupMenu","href":"neTabControl.TneTabControl.DisablePopupMenu.htm"}
,{"title":"TneTabControl.DoChange","href":"neTabControl.TneTabControl.DoChange.htm"}
,{"title":"TneTabControl.fCloseAllOtherTabsLabel","href":"neTabControl.TneTabControl.fCloseAllOtherTabsLabel.htm"}
,{"title":"TneTabControl.fCloseImageHover","href":"neTabControl.TneTabControl.fCloseImageHover.htm"}
,{"title":"TneTabControl.fCloseImageNormal","href":"neTabControl.TneTabControl.fCloseImageNormal.htm"}
,{"title":"TneTabControl.fCloseImagePressed","href":"neTabControl.TneTabControl.fCloseImagePressed.htm"}
,{"title":"TneTabControl.fCloseTabLabel","href":"neTabControl.TneTabControl.fCloseTabLabel.htm"}
,{"title":"TneTabControl.fCloseTabOnDoubleClick","href":"neTabControl.TneTabControl.fCloseTabOnDoubleClick.htm"}
,{"title":"TneTabControl.fCurrentNETabItem","href":"neTabControl.TneTabControl.fCurrentNETabItem.htm"}
,{"title":"TneTabControl.fDictionaryFrames","href":"neTabControl.TneTabControl.fDictionaryFrames.htm"}
,{"title":"TneTabControl.fDictionaryTabs","href":"neTabControl.TneTabControl.fDictionaryTabs.htm"}
,{"title":"TneTabControl.fDisablePopupMenu","href":"neTabControl.TneTabControl.fDisablePopupMenu.htm"}
,{"title":"TneTabControl.fHintPanel","href":"neTabControl.TneTabControl.fHintPanel.htm"}
,{"title":"TneTabControl.fHintPopup","href":"neTabControl.TneTabControl.fHintPopup.htm"}
,{"title":"TneTabControl.fHintShowDelay","href":"neTabControl.TneTabControl.fHintShowDelay.htm"}
,{"title":"TneTabControl.fHintStyle","href":"neTabControl.TneTabControl.fHintStyle.htm"}
,{"title":"TneTabControl.fHintTimer","href":"neTabControl.TneTabControl.fHintTimer.htm"}
,{"title":"TneTabControl.fHistoryTags","href":"neTabControl.TneTabControl.fHistoryTags.htm"}
,{"title":"TneTabControl.FindTabOrderFromTag(string)","href":"neTabControl.TneTabControl.FindTabOrderFromTag.htm"}
,{"title":"TneTabControl.FindTagFromTabOrder(integer)","href":"neTabControl.TneTabControl.FindTagFromTabOrder.htm"}
,{"title":"TneTabControl.fMaxTabWidth","href":"neTabControl.TneTabControl.fMaxTabWidth.htm"}
,{"title":"TneTabControl.fMinTabWidth","href":"neTabControl.TneTabControl.fMinTabWidth.htm"}
,{"title":"TneTabControl.fOnAfterDelete","href":"neTabControl.TneTabControl.fOnAfterDelete.htm"}
,{"title":"TneTabControl.fOnBeforeDelete","href":"neTabControl.TneTabControl.fOnBeforeDelete.htm"}
,{"title":"TneTabControl.fPopupAfterDefaultMenu","href":"neTabControl.TneTabControl.fPopupAfterDefaultMenu.htm"}
,{"title":"TneTabControl.fPopupBeforeDefaultMenu","href":"neTabControl.TneTabControl.fPopupBeforeDefaultMenu.htm"}
,{"title":"TneTabControl.fVersion","href":"neTabControl.TneTabControl.fVersion.htm"}
,{"title":"TneTabControl.GetActiveTag","href":"neTabControl.TneTabControl.GetActiveTag.htm"}
,{"title":"TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"TneTabControl.GetLastVisitedTag","href":"neTabControl.TneTabControl.GetLastVisitedTag.htm"}
,{"title":"TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"TneTabControl.GetTabsTags","href":"neTabControl.TneTabControl.GetTabsTags.htm"}
,{"title":"TneTabControl.GetTabsText","href":"neTabControl.TneTabControl.GetTabsText.htm"}
,{"title":"TneTabControl.GetVersion","href":"neTabControl.TneTabControl.GetVersion.htm"}
,{"title":"TneTabControl.HintShowDelay","href":"neTabControl.TneTabControl.HintShowDelay.htm"}
,{"title":"TneTabControl.HintStyle","href":"neTabControl.TneTabControl.HintStyle.htm"}
,{"title":"TneTabControl.InsertTab(string,Integer,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTFrame).htm"}
,{"title":"TneTabControl.InsertTab(string,Integer,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTneTabItem%2CTFrame).htm"}
,{"title":"TneTabControl.MaxTabWidth","href":"neTabControl.TneTabControl.MaxTabWidth.htm"}
,{"title":"TneTabControl.MinTabWidth","href":"neTabControl.TneTabControl.MinTabWidth.htm"}
,{"title":"TneTabControl.MouseEnterTabItem(TObject)","href":"neTabControl.TneTabControl.MouseEnterTabItem.htm"}
,{"title":"TneTabControl.MouseExitTabItem","href":"neTabControl.TneTabControl.MouseExitTabItem.htm"}
,{"title":"TneTabControl.MouseMoveOverTabItem(string,Single,Single)","href":"neTabControl.TneTabControl.MouseMoveOverTabItem.htm"}
,{"title":"TneTabControl.OnAfterDelete","href":"neTabControl.TneTabControl.OnAfterDelete.htm"}
,{"title":"TneTabControl.OnBeforeDelete","href":"neTabControl.TneTabControl.OnBeforeDelete.htm"}
,{"title":"TneTabControl.OnHintTimer(TObject)","href":"neTabControl.TneTabControl.OnHintTimer.htm"}
,{"title":"TneTabControl.OnPopUpChangeTab(TObject)","href":"neTabControl.TneTabControl.OnPopUpChangeTab.htm"}
,{"title":"TneTabControl.OnPopUpMenuClose(TObject)","href":"neTabControl.TneTabControl.OnPopUpMenuClose.htm"}
,{"title":"TneTabControl.OnPopUpMenuCloseAllOtherTabs(TObject)","href":"neTabControl.TneTabControl.OnPopUpMenuCloseAllOtherTabs.htm"}
,{"title":"TneTabControl.PopupAfterDefault","href":"neTabControl.TneTabControl.PopupAfterDefault.htm"}
,{"title":"TneTabControl.PopupBeforeDefault","href":"neTabControl.TneTabControl.PopupBeforeDefault.htm"}
,{"title":"TneTabControl.SaveTabs(TExportElementsSet,TSetOfString,TStringList)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"TneTabControl.SetActiveTab(string)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
,{"title":"TneTabControl.SetHintShowDelay(integer)","href":"neTabControl.TneTabControl.SetHintShowDelay.htm"}
,{"title":"TneTabControl.SetHintSTyle(THintStyle)","href":"neTabControl.TneTabControl.SetHintSTyle.htm"}
,{"title":"TneTabControl.SetMaxTabWidth(Single)","href":"neTabControl.TneTabControl.SetMaxTabWidth.htm"}
,{"title":"TneTabControl.SetMinTabWidth(Single)","href":"neTabControl.TneTabControl.SetMinTabWidth.htm"}
,{"title":"TneTabControl.ShowPopUpMenu(TneTabItem,Single,Single)","href":"neTabControl.TneTabControl.ShowPopUpMenu.htm"}
,{"title":"TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"TneTabItem","href":"neTabControl.TneTabItem.htm"}
,{"title":"TneTabItem.AdjustTabWidth(single,Single)","href":"neTabControl.TneTabItem.AdjustTabWidth.htm"}
,{"title":"TneTabItem.ApplyStyle","href":"neTabControl.TneTabItem.ApplyStyle.htm"}
,{"title":"TneTabItem.CanClose","href":"neTabControl.TneTabItem.CanClose.htm"}
,{"title":"TneTabItem.CloseImageHover","href":"neTabControl.TneTabItem.CloseImageHover.htm"}
,{"title":"TneTabItem.CloseImageNormal","href":"neTabControl.TneTabItem.CloseImageNormal.htm"}
,{"title":"TneTabItem.CloseImagePressed","href":"neTabControl.TneTabItem.CloseImagePressed.htm"}
,{"title":"TneTabItem.Create(TComponent)","href":"neTabControl.TneTabItem.Create.htm"}
,{"title":"TneTabItem.DblClick","href":"neTabControl.TneTabItem.DblClick.htm"}
,{"title":"TneTabItem.Deleted","href":"neTabControl.TneTabItem.Deleted.htm"}
,{"title":"TneTabItem.fCanClose","href":"neTabControl.TneTabItem.fCanClose.htm"}
,{"title":"TneTabItem.fCloseImageHover","href":"neTabControl.TneTabItem.fCloseImageHover.htm"}
,{"title":"TneTabItem.fCloseImageNormal","href":"neTabControl.TneTabItem.fCloseImageNormal.htm"}
,{"title":"TneTabItem.fCloseImagePressed","href":"neTabControl.TneTabItem.fCloseImagePressed.htm"}
,{"title":"TneTabItem.fDeleted","href":"neTabControl.TneTabItem.fDeleted.htm"}
,{"title":"TneTabItem.fIcon","href":"neTabControl.TneTabItem.fIcon.htm"}
,{"title":"TneTabItem.fIdentifier","href":"neTabControl.TneTabItem.fIdentifier.htm"}
,{"title":"TneTabItem.fIsMousePressed","href":"neTabControl.TneTabItem.fIsMousePressed.htm"}
,{"title":"TneTabItem.fShowIcon","href":"neTabControl.TneTabItem.fShowIcon.htm"}
,{"title":"TneTabItem.fTabControlParent","href":"neTabControl.TneTabItem.fTabControlParent.htm"}
,{"title":"TneTabItem.fTagVariant","href":"neTabControl.TneTabItem.fTagVariant.htm"}
,{"title":"TneTabItem.fVersion","href":"neTabControl.TneTabItem.fVersion.htm"}
,{"title":"TneTabItem.GetVersion","href":"neTabControl.TneTabItem.GetVersion.htm"}
,{"title":"TneTabItem.Icon","href":"neTabControl.TneTabItem.Icon.htm"}
,{"title":"TneTabItem.Identifier","href":"neTabControl.TneTabItem.Identifier.htm"}
,{"title":"TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseClick.htm"}
,{"title":"TneTabItem.MouseDown(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseDown.htm"}
,{"title":"TneTabItem.MouseUp(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseUp.htm"}
,{"title":"TneTabItem.NewOnMouseEnter(TObject)","href":"neTabControl.TneTabItem.NewOnMouseEnter.htm"}
,{"title":"TneTabItem.NewOnMouseLeave(TObject)","href":"neTabControl.TneTabItem.NewOnMouseLeave.htm"}
,{"title":"TneTabItem.NewOnMouseMove(TObject,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.NewOnMouseMove.htm"}
,{"title":"TneTabItem.OnCloseImageClick(TObject)","href":"neTabControl.TneTabItem.OnCloseImageClick.htm"}
,{"title":"TneTabItem.OnCloseImageHoverClick(TObject)","href":"neTabControl.TneTabItem.OnCloseImageHoverClick.htm"}
,{"title":"TneTabItem.OnCloseImageLeave(TObject)","href":"neTabControl.TneTabItem.OnCloseImageLeave.htm"}
,{"title":"TneTabItem.OnCloseImageMouseDown(TObject,TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.OnCloseImageMouseDown.htm"}
,{"title":"TneTabItem.OnCloseImageMouseUp(TObject,TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.OnCloseImageMouseUp.htm"}
,{"title":"TneTabItem.SetCanClose(Boolean)","href":"neTabControl.TneTabItem.SetCanClose.htm"}
,{"title":"TneTabItem.SetCloseImageHover(TBitmap)","href":"neTabControl.TneTabItem.SetCloseImageHover.htm"}
,{"title":"TneTabItem.SetCloseImageNormal(TBitmap)","href":"neTabControl.TneTabItem.SetCloseImageNormal.htm"}
,{"title":"TneTabItem.SetCloseImagePressed(TBitMap)","href":"neTabControl.TneTabItem.SetCloseImagePressed.htm"}
,{"title":"TneTabItem.SetIcon(TBitmap)","href":"neTabControl.TneTabItem.SetIcon.htm"}
,{"title":"TneTabItem.SetShowIcon(Boolean)","href":"neTabControl.TneTabItem.SetShowIcon.htm"}
,{"title":"TneTabItem.ShowIcon","href":"neTabControl.TneTabItem.ShowIcon.htm"}
,{"title":"TneTabItem.TabControlParent","href":"neTabControl.TneTabItem.TabControlParent.htm"}
,{"title":"TneTabItem.TagVariant","href":"neTabControl.TneTabItem.TagVariant.htm"}
,{"title":"TneTabItem.Version","href":"neTabControl.TneTabItem.Version.htm"}
,{"title":"TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
,{"title":"TSetOfString","href":"neTabControl.TSetOfString.htm"}
]