[{"title":"BugVersion","href":"neTabTypes.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabGeneralUtils.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabItem.BugVersion.htm"}
,{"title":"FindParentForm(TFmxObject)","href":"neTabGeneralUtils.FindParentForm.htm"}
,{"title":"GetTabControl(TClass)","href":"neTabControl.GetTabControl.htm"}
,{"title":"LoadImageFromResources(string,TBitmap)","href":"neTabGeneralUtils.LoadImageFromResources.htm"}
,{"title":"MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabTypes.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabItem.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabGeneralUtils.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neTabGeneralUtils.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabItem.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabTypes.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabControl.MinorVersion.htm"}
,{"title":"neTabControl","href":"neTabControl.htm"}
,{"title":"neTabControl.TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"neTabControl.TneTabPosition","href":"neTabControl.TneTabPosition.htm"}
,{"title":"neTabControl.TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"neTabControl.TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"neTabControl.TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"neTabControl.TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"neTabControl.TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"neTabControl.TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"neTabControl.TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"neTabControl.TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"neTabControl.TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"neTabControlPackage","href":"neTabControlPackage.htm"}
,{"title":"neTabGeneralUtils","href":"neTabGeneralUtils.htm"}
,{"title":"neTabItem","href":"neTabItem.htm"}
,{"title":"neTabItem.TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"neTabItem.TMouseState","href":"neTabItem.TMouseState.htm"}
,{"title":"neTabItem.TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm"}
,{"title":"neTabItem.TneControl","href":"neTabItem.TneControl.htm"}
,{"title":"neTabItem.TneTabItem","href":"neTabItem.TneTabItem.htm"}
,{"title":"neTabTypes","href":"neTabTypes.htm"}
,{"title":"neTabTypes.TExportElement","href":"neTabTypes.TExportElement.htm"}
,{"title":"neTabTypes.TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"neTabTypes.THistoryClass","href":"neTabTypes.THistoryClass.htm"}
,{"title":"neTabTypes.TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm"}
,{"title":"neTabTypes.TneTimer","href":"neTabTypes.TneTimer.htm"}
,{"title":"neTabTypes.TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
,{"title":"Register","href":"neTabControl.Register.htm"}
,{"title":"register","href":"neTabItem.register.htm"}
,{"title":"SCloseAllTabs","href":"neTabTypes.SCloseAllTabs.htm"}
,{"title":"SCloseOtherTabs","href":"neTabTypes.SCloseOtherTabs.htm"}
,{"title":"SCloseTab","href":"neTabTypes.SCloseTab.htm"}
,{"title":"TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImageHover","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImageNormal","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImagePressed","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TExportElement","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTagFloat","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTagString","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTitle","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"THistoryClass","href":"neTabTypes.THistoryClass.htm"}
,{"title":"THistoryClass.AddHistory(string)","href":"neTabTypes.THistoryClass.AddHistory.htm"}
,{"title":"THistoryClass.Create","href":"neTabTypes.THistoryClass.Create.htm"}
,{"title":"THistoryClass.DeleteHistory(string)","href":"neTabTypes.THistoryClass.DeleteHistory.htm"}
,{"title":"THistoryClass.Destroy","href":"neTabTypes.THistoryClass.Destroy.htm"}
,{"title":"THistoryClass.GetLastEntry","href":"neTabTypes.THistoryClass.GetLastEntry.htm"}
,{"title":"TMouseState","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msDown","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msHover","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msNone","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msUp","href":"neTabItem.TMouseState.htm"}
,{"title":"TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm"}
,{"title":"TneCloseImageControl.CloseImage","href":"neTabItem.TneCloseImageControl.CloseImage.htm"}
,{"title":"TneCloseImageControl.Create(TComponent)","href":"neTabItem.TneCloseImageControl.Create.htm"}
,{"title":"TneCloseImageControl.Destroy","href":"neTabItem.TneCloseImageControl.Destroy.htm"}
,{"title":"TneCloseImageControl.SetCloseImage(TBitmap)","href":"neTabItem.TneCloseImageControl.SetCloseImage.htm"}
,{"title":"TneControl","href":"neTabItem.TneControl.htm"}
,{"title":"TneControl.InnerControl","href":"neTabItem.TneControl.InnerControl.htm"}
,{"title":"TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm"}
,{"title":"TneNotificationClass.Action","href":"neTabTypes.TneNotificationClass.Action.htm"}
,{"title":"TneNotificationClass.Point","href":"neTabTypes.TneNotificationClass.Point.htm"}
,{"title":"TneNotificationClass.PopupAfter","href":"neTabTypes.TneNotificationClass.PopupAfter.htm"}
,{"title":"TneNotificationClass.PopupBefore","href":"neTabTypes.TneNotificationClass.PopupBefore.htm"}
,{"title":"TneNotificationClass.PopupDefault","href":"neTabTypes.TneNotificationClass.PopupDefault.htm"}
,{"title":"TneNotificationClass.Sender","href":"neTabTypes.TneNotificationClass.Sender.htm"}
,{"title":"TneNotificationClass.Value","href":"neTabTypes.TneNotificationClass.Value.htm"}
,{"title":"TneNotificationClass.ValueInt","href":"neTabTypes.TneNotificationClass.ValueInt.htm"}
,{"title":"TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneSibebarControlPosition.sbLeft","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneSibebarControlPosition.sbRight","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"TneTabControl.ActiveTab","href":"neTabControl.TneTabControl.ActiveTab.htm"}
,{"title":"TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"TneTabControl.AddSidebarControl(TControl,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.AddSidebarControl.htm"}
,{"title":"TneTabControl.AddTab(string)","href":"neTabControl.TneTabControl.AddTab(string).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem,TFrame).htm"}
,{"title":"TneTabControl.Align","href":"neTabControl.TneTabControl.Align.htm"}
,{"title":"TneTabControl.Anchors","href":"neTabControl.TneTabControl.Anchors.htm"}
,{"title":"TneTabControl.CanParentFocus","href":"neTabControl.TneTabControl.CanParentFocus.htm"}
,{"title":"TneTabControl.ClipChildren","href":"neTabControl.TneTabControl.ClipChildren.htm"}
,{"title":"TneTabControl.ClipParent","href":"neTabControl.TneTabControl.ClipParent.htm"}
,{"title":"TneTabControl.CloseAllOtherTabsText","href":"neTabControl.TneTabControl.CloseAllOtherTabsText.htm"}
,{"title":"TneTabControl.CloseAllTabsText","href":"neTabControl.TneTabControl.CloseAllTabsText.htm"}
,{"title":"TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"TneTabControl.CloseTabText","href":"neTabControl.TneTabControl.CloseTabText.htm"}
,{"title":"TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"TneTabControl.Cursor","href":"neTabControl.TneTabControl.Cursor.htm"}
,{"title":"TneTabControl.DeleteSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.DeleteSidebarControl.htm"}
,{"title":"TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
,{"title":"TneTabControl.DisableFocusEffect","href":"neTabControl.TneTabControl.DisableFocusEffect.htm"}
,{"title":"TneTabControl.DragMode","href":"neTabControl.TneTabControl.DragMode.htm"}
,{"title":"TneTabControl.Enabled","href":"neTabControl.TneTabControl.Enabled.htm"}
,{"title":"TneTabControl.EnableDragHighlight","href":"neTabControl.TneTabControl.EnableDragHighlight.htm"}
,{"title":"TneTabControl.GetControl(string)","href":"neTabControl.TneTabControl.GetControl.htm"}
,{"title":"TneTabControl.GetSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControl.htm"}
,{"title":"TneTabControl.GetSidebarControlCount(TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControlCount.htm"}
,{"title":"TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"TneTabControl.GetTabItemsList(TList)","href":"neTabControl.TneTabControl.GetTabItemsList.htm"}
,{"title":"TneTabControl.GetTag(Integer)","href":"neTabControl.TneTabControl.GetTag.htm"}
,{"title":"TneTabControl.GetTagList(TStringList)","href":"neTabControl.TneTabControl.GetTagList.htm"}
,{"title":"TneTabControl.Height","href":"neTabControl.TneTabControl.Height.htm"}
,{"title":"TneTabControl.HitTest","href":"neTabControl.TneTabControl.HitTest.htm"}
,{"title":"TneTabControl.InsertTab(string,integer)","href":"neTabControl.TneTabControl.InsertTab(string,integer).htm"}
,{"title":"TneTabControl.InsertTab(string,integer,TneTabItem)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem).htm"}
,{"title":"TneTabControl.InsertTab(string,integer,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem,TFrame).htm"}
,{"title":"TneTabControl.Locked","href":"neTabControl.TneTabControl.Locked.htm"}
,{"title":"TneTabControl.Margins","href":"neTabControl.TneTabControl.Margins.htm"}
,{"title":"TneTabControl.OnAfterAddItem","href":"neTabControl.TneTabControl.OnAfterAddItem.htm"}
,{"title":"TneTabControl.OnAfterAddSidebarControl","href":"neTabControl.TneTabControl.OnAfterAddSidebarControl.htm"}
,{"title":"TneTabControl.OnAfterDeleteItem","href":"neTabControl.TneTabControl.OnAfterDeleteItem.htm"}
,{"title":"TneTabControl.OnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl.htm"}
,{"title":"TneTabControl.OnApplyStyleLookup","href":"neTabControl.TneTabControl.OnApplyStyleLookup.htm"}
,{"title":"TneTabControl.OnBeforeAddItem","href":"neTabControl.TneTabControl.OnBeforeAddItem.htm"}
,{"title":"TneTabControl.OnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.OnBeforeAddSidebarControl.htm"}
,{"title":"TneTabControl.OnBeforeDeleteItem","href":"neTabControl.TneTabControl.OnBeforeDeleteItem.htm"}
,{"title":"TneTabControl.OnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl.htm"}
,{"title":"TneTabControl.OnBeforePopupMenu","href":"neTabControl.TneTabControl.OnBeforePopupMenu.htm"}
,{"title":"TneTabControl.OnCanFocus","href":"neTabControl.TneTabControl.OnCanFocus.htm"}
,{"title":"TneTabControl.OnChange","href":"neTabControl.TneTabControl.OnChange.htm"}
,{"title":"TneTabControl.OnClick","href":"neTabControl.TneTabControl.OnClick.htm"}
,{"title":"TneTabControl.OnDblClick","href":"neTabControl.TneTabControl.OnDblClick.htm"}
,{"title":"TneTabControl.OnDragDrop","href":"neTabControl.TneTabControl.OnDragDrop.htm"}
,{"title":"TneTabControl.OnDragEnd","href":"neTabControl.TneTabControl.OnDragEnd.htm"}
,{"title":"TneTabControl.OnDragEnter","href":"neTabControl.TneTabControl.OnDragEnter.htm"}
,{"title":"TneTabControl.OnDragLeave","href":"neTabControl.TneTabControl.OnDragLeave.htm"}
,{"title":"TneTabControl.OnDragOver","href":"neTabControl.TneTabControl.OnDragOver.htm"}
,{"title":"TneTabControl.OnEnter","href":"neTabControl.TneTabControl.OnEnter.htm"}
,{"title":"TneTabControl.OnExit","href":"neTabControl.TneTabControl.OnExit.htm"}
,{"title":"TneTabControl.OnKeyDown","href":"neTabControl.TneTabControl.OnKeyDown.htm"}
,{"title":"TneTabControl.OnKeyUp","href":"neTabControl.TneTabControl.OnKeyUp.htm"}
,{"title":"TneTabControl.OnMouseDown","href":"neTabControl.TneTabControl.OnMouseDown.htm"}
,{"title":"TneTabControl.OnMouseEnter","href":"neTabControl.TneTabControl.OnMouseEnter.htm"}
,{"title":"TneTabControl.OnMouseLeave","href":"neTabControl.TneTabControl.OnMouseLeave.htm"}
,{"title":"TneTabControl.OnMouseMove","href":"neTabControl.TneTabControl.OnMouseMove.htm"}
,{"title":"TneTabControl.OnMouseUp","href":"neTabControl.TneTabControl.OnMouseUp.htm"}
,{"title":"TneTabControl.OnMouseWheel","href":"neTabControl.TneTabControl.OnMouseWheel.htm"}
,{"title":"TneTabControl.OnPaint","href":"neTabControl.TneTabControl.OnPaint.htm"}
,{"title":"TneTabControl.OnPainting","href":"neTabControl.TneTabControl.OnPainting.htm"}
,{"title":"TneTabControl.OnResize","href":"neTabControl.TneTabControl.OnResize.htm"}
,{"title":"TneTabControl.Opacity","href":"neTabControl.TneTabControl.Opacity.htm"}
,{"title":"TneTabControl.Padding","href":"neTabControl.TneTabControl.Padding.htm"}
,{"title":"TneTabControl.PopupMenu","href":"neTabControl.TneTabControl.PopupMenu.htm"}
,{"title":"TneTabControl.Position","href":"neTabControl.TneTabControl.Position.htm"}
,{"title":"TneTabControl.RefreshControl(string)","href":"neTabControl.TneTabControl.RefreshControl(string).htm"}
,{"title":"TneTabControl.RefreshTabHeight(string)","href":"neTabControl.TneTabControl.RefreshTabHeight(string).htm"}
,{"title":"TneTabControl.RotationAngle","href":"neTabControl.TneTabControl.RotationAngle.htm"}
,{"title":"TneTabControl.RotationCenter","href":"neTabControl.TneTabControl.RotationCenter.htm"}
,{"title":"TneTabControl.SaveTabs(TExportElements,TSetOfStrings,TStringList)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"TneTabControl.Scale","href":"neTabControl.TneTabControl.Scale.htm"}
,{"title":"TneTabControl.Size","href":"neTabControl.TneTabControl.Size.htm"}
,{"title":"TneTabControl.StyleLookup","href":"neTabControl.TneTabControl.StyleLookup.htm"}
,{"title":"TneTabControl.TabCount","href":"neTabControl.TneTabControl.TabCount.htm"}
,{"title":"TneTabControl.TabHeight","href":"neTabControl.TneTabControl.TabHeight.htm"}
,{"title":"TneTabControl.TabOrder","href":"neTabControl.TneTabControl.TabOrder.htm"}
,{"title":"TneTabControl.TabPosition","href":"neTabControl.TneTabControl.TabPosition.htm"}
,{"title":"TneTabControl.ToggleVisible(Boolean,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.ToggleVisible.htm"}
,{"title":"TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"TneTabControl.Visible","href":"neTabControl.TneTabControl.Visible.htm"}
,{"title":"TneTabControl.Width","href":"neTabControl.TneTabControl.Width.htm"}
,{"title":"TneTabItem","href":"neTabItem.TneTabItem.htm"}
,{"title":"TneTabItem.ApplyStyle","href":"neTabItem.TneTabItem.ApplyStyle.htm"}
,{"title":"TneTabItem.CanClose","href":"neTabItem.TneTabItem.CanClose.htm"}
,{"title":"TneTabItem.CloseImageHover","href":"neTabItem.TneTabItem.CloseImageHover.htm"}
,{"title":"TneTabItem.CloseImageNormal","href":"neTabItem.TneTabItem.CloseImageNormal.htm"}
,{"title":"TneTabItem.CloseImagePressed","href":"neTabItem.TneTabItem.CloseImagePressed.htm"}
,{"title":"TneTabItem.ControlToShow","href":"neTabItem.TneTabItem.ControlToShow.htm"}
,{"title":"TneTabItem.Create(TComponent)","href":"neTabItem.TneTabItem.Create.htm"}
,{"title":"TneTabItem.Destroy","href":"neTabItem.TneTabItem.Destroy.htm"}
,{"title":"TneTabItem.DoMouseLeave","href":"neTabItem.TneTabItem.DoMouseLeave.htm"}
,{"title":"TneTabItem.MaxTabWidth","href":"neTabItem.TneTabItem.MaxTabWidth.htm"}
,{"title":"TneTabItem.MinTabWidth","href":"neTabItem.TneTabItem.MinTabWidth.htm"}
,{"title":"TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseClick.htm"}
,{"title":"TneTabItem.MouseMove(TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseMove.htm"}
,{"title":"TneTabItem.PopupMenuAfterDefault","href":"neTabItem.TneTabItem.PopupMenuAfterDefault.htm"}
,{"title":"TneTabItem.PopupMenuBeforeDefault","href":"neTabItem.TneTabItem.PopupMenuBeforeDefault.htm"}
,{"title":"TneTabItem.Provider","href":"neTabItem.TneTabItem.Provider.htm"}
,{"title":"TneTabItem.RefreshControl","href":"neTabItem.TneTabItem.RefreshControl.htm"}
,{"title":"TneTabItem.ShowControl","href":"neTabItem.TneTabItem.ShowControl.htm"}
,{"title":"TneTabItem.ShowPopupMenu","href":"neTabItem.TneTabItem.ShowPopupMenu.htm"}
,{"title":"TneTabItem.TabTag","href":"neTabItem.TneTabItem.TabTag.htm"}
,{"title":"TneTabItem.TabWidth","href":"neTabItem.TneTabItem.TabWidth.htm"}
,{"title":"TneTabPosition","href":"neTabControl.TneTabPosition.htm"}
,{"title":"TneTabPosition.Bottom","href":"neTabControl.TneTabPosition.htm"}
,{"title":"TneTabPosition.Left","href":"neTabControl.TneTabPosition.htm"}
,{"title":"TneTabPosition.Right","href":"neTabControl.TneTabPosition.htm"}
,{"title":"TneTabPosition.Top","href":"neTabControl.TneTabPosition.htm"}
,{"title":"TneTimer","href":"neTabTypes.TneTimer.htm"}
,{"title":"TneTimer.Action","href":"neTabTypes.TneTimer.Action.htm"}
,{"title":"TneTimer.Value","href":"neTabTypes.TneTimer.Value.htm"}
,{"title":"TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
]