[{"title":"BugVersion","href":"neTabGeneralUtils.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabTypes.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"BugVersion","href":"neTabItem.BugVersion.htm"}
,{"title":"FindParentForm(TFmxObject)","href":"neTabGeneralUtils.FindParentForm.htm"}
,{"title":"GetTabControl(TClass)","href":"neTabControl.GetTabControl.htm"}
,{"title":"LoadImageFromResources(string,TBitmap)","href":"neTabGeneralUtils.LoadImageFromResources.htm"}
,{"title":"MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabTypes.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabGeneralUtils.MajorVersion.htm"}
,{"title":"MajorVersion","href":"neTabItem.MajorVersion.htm"}
,{"title":"MinorVersion","href":"neTabGeneralUtils.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabControl.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabTypes.MinorVersion.htm"}
,{"title":"MinorVersion","href":"neTabItem.MinorVersion.htm"}
,{"title":"neTabControl","href":"neTabControl.htm"}
,{"title":"neTabControl.TneDoChangeType","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"neTabControl.TneHintType","href":"neTabControl.TneHintType.htm"}
,{"title":"neTabControl.TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"neTabControl.TneTabOrientation","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"neTabControl.TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"neTabControl.TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"neTabControl.TOnAfterCloseAllItems","href":"neTabControl.TOnAfterCloseAllItems.htm"}
,{"title":"neTabControl.TOnAfterCloseOtherItems","href":"neTabControl.TOnAfterCloseOtherItems.htm"}
,{"title":"neTabControl.TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"neTabControl.TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"neTabControl.TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"neTabControl.TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"neTabControl.TOnBeforeCloseAllItems","href":"neTabControl.TOnBeforeCloseAllItems.htm"}
,{"title":"neTabControl.TOnBeforeCloseOtherItems","href":"neTabControl.TOnBeforeCloseOtherItems.htm"}
,{"title":"neTabControl.TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"neTabControl.TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"neTabControl.TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"neTabControl.TOnCustomHint","href":"neTabControl.TOnCustomHint.htm"}
,{"title":"neTabControlPackage","href":"neTabControlPackage.htm"}
,{"title":"neTabGeneralUtils","href":"neTabGeneralUtils.htm"}
,{"title":"neTabItem","href":"neTabItem.htm"}
,{"title":"neTabItem.TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"neTabItem.TMouseState","href":"neTabItem.TMouseState.htm"}
,{"title":"neTabItem.TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm"}
,{"title":"neTabItem.TneControl","href":"neTabItem.TneControl.htm"}
,{"title":"neTabItem.TneTabItem","href":"neTabItem.TneTabItem.htm"}
,{"title":"neTabTypes","href":"neTabTypes.htm"}
,{"title":"neTabTypes.TExportElement","href":"neTabTypes.TExportElement.htm"}
,{"title":"neTabTypes.TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"neTabTypes.THistoryClass","href":"neTabTypes.THistoryClass.htm"}
,{"title":"neTabTypes.TneHintTimer","href":"neTabTypes.TneHintTimer.htm"}
,{"title":"neTabTypes.TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm"}
,{"title":"neTabTypes.TneTimer","href":"neTabTypes.TneTimer.htm"}
,{"title":"neTabTypes.TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
,{"title":"neTabTypes.TShowTabAnimation","href":"neTabTypes.TShowTabAnimation.htm"}
,{"title":"Register","href":"neTabControl.Register.htm"}
,{"title":"register","href":"neTabItem.register.htm"}
,{"title":"SCloseAllTabs","href":"neTabTypes.SCloseAllTabs.htm"}
,{"title":"SCloseOtherTabs","href":"neTabTypes.SCloseOtherTabs.htm"}
,{"title":"SCloseTab","href":"neTabTypes.SCloseTab.htm"}
,{"title":"TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImageHover","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImageNormal","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TCloseImagesType.ImagePressed","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TExportElement","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTagFloat","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTagString","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElement.expTitle","href":"neTabTypes.TExportElement.htm"}
,{"title":"TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"THistoryClass","href":"neTabTypes.THistoryClass.htm"}
,{"title":"THistoryClass.AddHistory(string)","href":"neTabTypes.THistoryClass.AddHistory.htm"}
,{"title":"THistoryClass.Create","href":"neTabTypes.THistoryClass.Create.htm"}
,{"title":"THistoryClass.DeleteHistory(string)","href":"neTabTypes.THistoryClass.DeleteHistory.htm"}
,{"title":"THistoryClass.Destroy","href":"neTabTypes.THistoryClass.Destroy.htm"}
,{"title":"THistoryClass.fHistoryList","href":"neTabTypes.THistoryClass.fHistoryList.htm"}
,{"title":"THistoryClass.GetLastEntry","href":"neTabTypes.THistoryClass.GetLastEntry.htm"}
,{"title":"TMouseState","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msDown","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msHover","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msNone","href":"neTabItem.TMouseState.htm"}
,{"title":"TMouseState.msUp","href":"neTabItem.TMouseState.htm"}
,{"title":"TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm"}
,{"title":"TneCloseImageControl.CloseImage","href":"neTabItem.TneCloseImageControl.CloseImage.htm"}
,{"title":"TneCloseImageControl.Create(TComponent)","href":"neTabItem.TneCloseImageControl.Create.htm"}
,{"title":"TneCloseImageControl.Destroy","href":"neTabItem.TneCloseImageControl.Destroy.htm"}
,{"title":"TneCloseImageControl.DoMouseEnter","href":"neTabItem.TneCloseImageControl.DoMouseEnter.htm"}
,{"title":"TneCloseImageControl.DoMouseLeave","href":"neTabItem.TneCloseImageControl.DoMouseLeave.htm"}
,{"title":"TneCloseImageControl.fProvider","href":"neTabItem.TneCloseImageControl.fProvider.htm"}
,{"title":"TneCloseImageControl.GetCloseImage","href":"neTabItem.TneCloseImageControl.GetCloseImage.htm"}
,{"title":"TneCloseImageControl.MouseDown(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseDown.htm"}
,{"title":"TneCloseImageControl.MouseUp(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseUp.htm"}
,{"title":"TneCloseImageControl.NotifyTabItem(TIntAction)","href":"neTabItem.TneCloseImageControl.NotifyTabItem.htm"}
,{"title":"TneCloseImageControl.SetCloseImage(TBitmap)","href":"neTabItem.TneCloseImageControl.SetCloseImage.htm"}
,{"title":"TneControl","href":"neTabItem.TneControl.htm"}
,{"title":"TneControl.fControl","href":"neTabItem.TneControl.fControl.htm"}
,{"title":"TneControl.InnerControl","href":"neTabItem.TneControl.InnerControl.htm"}
,{"title":"TneDoChangeType","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"TneDoChangeType.dcMainTab","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"TneDoChangeType.dcTabBar","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"TneHintTimer","href":"neTabTypes.TneHintTimer.htm"}
,{"title":"TneHintTimer.MousePoint","href":"neTabTypes.TneHintTimer.MousePoint.htm"}
,{"title":"TneHintType","href":"neTabControl.TneHintType.htm"}
,{"title":"TneHintType.Custom","href":"neTabControl.TneHintType.htm"}
,{"title":"TneHintType.Off","href":"neTabControl.TneHintType.htm"}
,{"title":"TneHintType.Preview","href":"neTabControl.TneHintType.htm"}
,{"title":"TneHintType.Text","href":"neTabControl.TneHintType.htm"}
,{"title":"TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm"}
,{"title":"TneNotificationClass.Action","href":"neTabTypes.TneNotificationClass.Action.htm"}
,{"title":"TneNotificationClass.fActions","href":"neTabTypes.TneNotificationClass.fActions.htm"}
,{"title":"TneNotificationClass.fPoint","href":"neTabTypes.TneNotificationClass.fPoint.htm"}
,{"title":"TneNotificationClass.fPopupAfter","href":"neTabTypes.TneNotificationClass.fPopupAfter.htm"}
,{"title":"TneNotificationClass.fPopupBefore","href":"neTabTypes.TneNotificationClass.fPopupBefore.htm"}
,{"title":"TneNotificationClass.fPopupDefault","href":"neTabTypes.TneNotificationClass.fPopupDefault.htm"}
,{"title":"TneNotificationClass.fSender","href":"neTabTypes.TneNotificationClass.fSender.htm"}
,{"title":"TneNotificationClass.fValue","href":"neTabTypes.TneNotificationClass.fValue.htm"}
,{"title":"TneNotificationClass.fValueInt","href":"neTabTypes.TneNotificationClass.fValueInt.htm"}
,{"title":"TneNotificationClass.Point","href":"neTabTypes.TneNotificationClass.Point.htm"}
,{"title":"TneNotificationClass.PopupAfter","href":"neTabTypes.TneNotificationClass.PopupAfter.htm"}
,{"title":"TneNotificationClass.PopupBefore","href":"neTabTypes.TneNotificationClass.PopupBefore.htm"}
,{"title":"TneNotificationClass.PopupDefault","href":"neTabTypes.TneNotificationClass.PopupDefault.htm"}
,{"title":"TneNotificationClass.Sender","href":"neTabTypes.TneNotificationClass.Sender.htm"}
,{"title":"TneNotificationClass.Value","href":"neTabTypes.TneNotificationClass.Value.htm"}
,{"title":"TneNotificationClass.ValueInt","href":"neTabTypes.TneNotificationClass.ValueInt.htm"}
,{"title":"TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneSibebarControlPosition.sbLeft","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneSibebarControlPosition.sbRight","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneTabControl","href":"neTabControl.TneTabControl.htm"}
,{"title":"TneTabControl.ActiveTab","href":"neTabControl.TneTabControl.ActiveTab.htm"}
,{"title":"TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"TneTabControl.AddSidebarControl(TControl,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.AddSidebarControl.htm"}
,{"title":"TneTabControl.AddTab(string)","href":"neTabControl.TneTabControl.AddTab(string).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem).htm"}
,{"title":"TneTabControl.AddTab(string,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem,TFrame).htm"}
,{"title":"TneTabControl.Align","href":"neTabControl.TneTabControl.Align.htm"}
,{"title":"TneTabControl.Anchors","href":"neTabControl.TneTabControl.Anchors.htm"}
,{"title":"TneTabControl.CanParentFocus","href":"neTabControl.TneTabControl.CanParentFocus.htm"}
,{"title":"TneTabControl.ClipChildren","href":"neTabControl.TneTabControl.ClipChildren.htm"}
,{"title":"TneTabControl.ClipParent","href":"neTabControl.TneTabControl.ClipParent.htm"}
,{"title":"TneTabControl.CloseAllOtherTabsText","href":"neTabControl.TneTabControl.CloseAllOtherTabsText.htm"}
,{"title":"TneTabControl.CloseAllTabsText","href":"neTabControl.TneTabControl.CloseAllTabsText.htm"}
,{"title":"TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"TneTabControl.CloseTabText","href":"neTabControl.TneTabControl.CloseTabText.htm"}
,{"title":"TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"TneTabControl.Cursor","href":"neTabControl.TneTabControl.Cursor.htm"}
,{"title":"TneTabControl.DeleteAllTabs(Boolean)","href":"neTabControl.TneTabControl.DeleteAllTabs.htm"}
,{"title":"TneTabControl.DeleteSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.DeleteSidebarControl.htm"}
,{"title":"TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
,{"title":"TneTabControl.DisableFocusEffect","href":"neTabControl.TneTabControl.DisableFocusEffect.htm"}
,{"title":"TneTabControl.DoMainChange(TneDoChangeType)","href":"neTabControl.TneTabControl.DoMainChange.htm"}
,{"title":"TneTabControl.DragMode","href":"neTabControl.TneTabControl.DragMode.htm"}
,{"title":"TneTabControl.Enabled","href":"neTabControl.TneTabControl.Enabled.htm"}
,{"title":"TneTabControl.EnableDragHighlight","href":"neTabControl.TneTabControl.EnableDragHighlight.htm"}
,{"title":"TneTabControl.fActiveTab","href":"neTabControl.TneTabControl.fActiveTab.htm"}
,{"title":"TneTabControl.fActiveTag","href":"neTabControl.TneTabControl.fActiveTag.htm"}
,{"title":"TneTabControl.fCloseAllOtherTabsText","href":"neTabControl.TneTabControl.fCloseAllOtherTabsText.htm"}
,{"title":"TneTabControl.fCloseAllTabsText","href":"neTabControl.TneTabControl.fCloseAllTabsText.htm"}
,{"title":"TneTabControl.fCloseImageHover","href":"neTabControl.TneTabControl.fCloseImageHover.htm"}
,{"title":"TneTabControl.fCloseImageNormal","href":"neTabControl.TneTabControl.fCloseImageNormal.htm"}
,{"title":"TneTabControl.fCloseImagePressed","href":"neTabControl.TneTabControl.fCloseImagePressed.htm"}
,{"title":"TneTabControl.fCloseTabText","href":"neTabControl.TneTabControl.fCloseTabText.htm"}
,{"title":"TneTabControl.fCloseTimer","href":"neTabControl.TneTabControl.fCloseTimer.htm"}
,{"title":"TneTabControl.fFramesDictionary","href":"neTabControl.TneTabControl.fFramesDictionary.htm"}
,{"title":"TneTabControl.fHintInterval","href":"neTabControl.TneTabControl.fHintInterval.htm"}
,{"title":"TneTabControl.fHintType","href":"neTabControl.TneTabControl.fHintType.htm"}
,{"title":"TneTabControl.fHistoryList","href":"neTabControl.TneTabControl.fHistoryList.htm"}
,{"title":"TneTabControl.fInternalTimer","href":"neTabControl.TneTabControl.fInternalTimer.htm"}
,{"title":"TneTabControl.fLeftLayout","href":"neTabControl.TneTabControl.fLeftLayout.htm"}
,{"title":"TneTabControl.fLeftSidebarControls","href":"neTabControl.TneTabControl.fLeftSidebarControls.htm"}
,{"title":"TneTabControl.fMainControl","href":"neTabControl.TneTabControl.fMainControl.htm"}
,{"title":"TneTabControl.fMainGridLayout","href":"neTabControl.TneTabControl.fMainGridLayout.htm"}
,{"title":"TneTabControl.fMainLayout","href":"neTabControl.TneTabControl.fMainLayout.htm"}
,{"title":"TneTabControl.fMainTabsDictionary","href":"neTabControl.TneTabControl.fMainTabsDictionary.htm"}
,{"title":"TneTabControl.fNumofDoMainChangeCalls","href":"neTabControl.TneTabControl.fNumofDoMainChangeCalls.htm"}
,{"title":"TneTabControl.fOnAfterAddItem","href":"neTabControl.TneTabControl.fOnAfterAddItem.htm"}
,{"title":"TneTabControl.fOnAfterAddSidebarControl","href":"neTabControl.TneTabControl.fOnAfterAddSidebarControl.htm"}
,{"title":"TneTabControl.fOnAfterCloseAllItems","href":"neTabControl.TneTabControl.fOnAfterCloseAllItems.htm"}
,{"title":"TneTabControl.fOnAfterCloseOtherItems","href":"neTabControl.TneTabControl.fOnAfterCloseOtherItems.htm"}
,{"title":"TneTabControl.fOnAfterDeleteItem","href":"neTabControl.TneTabControl.fOnAfterDeleteItem.htm"}
,{"title":"TneTabControl.fOnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.fOnAfterDeleteSidebarControl.htm"}
,{"title":"TneTabControl.fOnBeforeAddItem","href":"neTabControl.TneTabControl.fOnBeforeAddItem.htm"}
,{"title":"TneTabControl.fOnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.fOnBeforeAddSidebarControl.htm"}
,{"title":"TneTabControl.fOnBeforeCloseAllItems","href":"neTabControl.TneTabControl.fOnBeforeCloseAllItems.htm"}
,{"title":"TneTabControl.fOnBeforeCloseOtherItems","href":"neTabControl.TneTabControl.fOnBeforeCloseOtherItems.htm"}
,{"title":"TneTabControl.fOnBeforeDeleteItem","href":"neTabControl.TneTabControl.fOnBeforeDeleteItem.htm"}
,{"title":"TneTabControl.fOnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.fOnBeforeDeleteSidebarControl.htm"}
,{"title":"TneTabControl.fOnBeforePopupMenu","href":"neTabControl.TneTabControl.fOnBeforePopupMenu.htm"}
,{"title":"TneTabControl.fOnChange","href":"neTabControl.TneTabControl.fOnChange.htm"}
,{"title":"TneTabControl.fOnCustomHint","href":"neTabControl.TneTabControl.fOnCustomHint.htm"}
,{"title":"TneTabControl.fPopup","href":"neTabControl.TneTabControl.fPopup.htm"}
,{"title":"TneTabControl.fRightLayout","href":"neTabControl.TneTabControl.fRightLayout.htm"}
,{"title":"TneTabControl.fRightSidebarControls","href":"neTabControl.TneTabControl.fRightSidebarControls.htm"}
,{"title":"TneTabControl.fSubscriber","href":"neTabControl.TneTabControl.fSubscriber.htm"}
,{"title":"TneTabControl.fTabAnimation","href":"neTabControl.TneTabControl.fTabAnimation.htm"}
,{"title":"TneTabControl.fTabAnimationDuration","href":"neTabControl.TneTabControl.fTabAnimationDuration.htm"}
,{"title":"TneTabControl.fTabAnimationInterpolation","href":"neTabControl.TneTabControl.fTabAnimationInterpolation.htm"}
,{"title":"TneTabControl.fTabAnimationType","href":"neTabControl.TneTabControl.fTabAnimationType.htm"}
,{"title":"TneTabControl.fTabBar","href":"neTabControl.TneTabControl.fTabBar.htm"}
,{"title":"TneTabControl.fTabHeight","href":"neTabControl.TneTabControl.fTabHeight.htm"}
,{"title":"TneTabControl.fTabOrientation","href":"neTabControl.TneTabControl.fTabOrientation.htm"}
,{"title":"TneTabControl.fTabPosition","href":"neTabControl.TneTabControl.fTabPosition.htm"}
,{"title":"TneTabControl.fTabsDictionary","href":"neTabControl.TneTabControl.fTabsDictionary.htm"}
,{"title":"TneTabControl.fTransitionType","href":"neTabControl.TneTabControl.fTransitionType.htm"}
,{"title":"TneTabControl.fVersion","href":"neTabControl.TneTabControl.fVersion.htm"}
,{"title":"TneTabControl.GetControl(string)","href":"neTabControl.TneTabControl.GetControl.htm"}
,{"title":"TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"TneTabControl.GetSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControl.htm"}
,{"title":"TneTabControl.GetSidebarControlCount(TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControlCount.htm"}
,{"title":"TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"TneTabControl.GetTabAnimation","href":"neTabControl.TneTabControl.GetTabAnimation.htm"}
,{"title":"TneTabControl.GetTabAnimationDuration","href":"neTabControl.TneTabControl.GetTabAnimationDuration.htm"}
,{"title":"TneTabControl.GetTabAnimationInterpolation","href":"neTabControl.TneTabControl.GetTabAnimationInterpolation.htm"}
,{"title":"TneTabControl.GetTabAnimationType","href":"neTabControl.TneTabControl.GetTabAnimationType.htm"}
,{"title":"TneTabControl.GetTabByIndex(Integer)","href":"neTabControl.TneTabControl.GetTabByIndex.htm"}
,{"title":"TneTabControl.GetTabCount","href":"neTabControl.TneTabControl.GetTabCount.htm"}
,{"title":"TneTabControl.GetTabItemsList(TList)","href":"neTabControl.TneTabControl.GetTabItemsList.htm"}
,{"title":"TneTabControl.GetTag(Integer)","href":"neTabControl.TneTabControl.GetTag.htm"}
,{"title":"TneTabControl.GetTagList(TStringList)","href":"neTabControl.TneTabControl.GetTagList.htm"}
,{"title":"TneTabControl.GetVersion","href":"neTabControl.TneTabControl.GetVersion.htm"}
,{"title":"TneTabControl.Height","href":"neTabControl.TneTabControl.Height.htm"}
,{"title":"TneTabControl.HintInterval","href":"neTabControl.TneTabControl.HintInterval.htm"}
,{"title":"TneTabControl.HintType","href":"neTabControl.TneTabControl.HintType.htm"}
,{"title":"TneTabControl.HitTest","href":"neTabControl.TneTabControl.HitTest.htm"}
,{"title":"TneTabControl.InsertTab(string,integer)","href":"neTabControl.TneTabControl.InsertTab(string,integer).htm"}
,{"title":"TneTabControl.InsertTab(string,integer,TneTabItem)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem).htm"}
,{"title":"TneTabControl.InsertTab(string,integer,TneTabItem,TFrame)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem,TFrame).htm"}
,{"title":"TneTabControl.Locked","href":"neTabControl.TneTabControl.Locked.htm"}
,{"title":"TneTabControl.Margins","href":"neTabControl.TneTabControl.Margins.htm"}
,{"title":"TneTabControl.OnAfterAddItem","href":"neTabControl.TneTabControl.OnAfterAddItem.htm"}
,{"title":"TneTabControl.OnAfterAddSidebarControl","href":"neTabControl.TneTabControl.OnAfterAddSidebarControl.htm"}
,{"title":"TneTabControl.OnAfterCloseAllItems","href":"neTabControl.TneTabControl.OnAfterCloseAllItems.htm"}
,{"title":"TneTabControl.OnAfterCloseOtherItems","href":"neTabControl.TneTabControl.OnAfterCloseOtherItems.htm"}
,{"title":"TneTabControl.OnAfterDeleteItem","href":"neTabControl.TneTabControl.OnAfterDeleteItem.htm"}
,{"title":"TneTabControl.OnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl.htm"}
,{"title":"TneTabControl.OnApplyStyleLookup","href":"neTabControl.TneTabControl.OnApplyStyleLookup.htm"}
,{"title":"TneTabControl.OnBeforeAddItem","href":"neTabControl.TneTabControl.OnBeforeAddItem.htm"}
,{"title":"TneTabControl.OnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.OnBeforeAddSidebarControl.htm"}
,{"title":"TneTabControl.OnBeforeCloseAllItems","href":"neTabControl.TneTabControl.OnBeforeCloseAllItems.htm"}
,{"title":"TneTabControl.OnBeforeCloseOtherItems","href":"neTabControl.TneTabControl.OnBeforeCloseOtherItems.htm"}
,{"title":"TneTabControl.OnBeforeDeleteItem","href":"neTabControl.TneTabControl.OnBeforeDeleteItem.htm"}
,{"title":"TneTabControl.OnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl.htm"}
,{"title":"TneTabControl.OnBeforePopupMenu","href":"neTabControl.TneTabControl.OnBeforePopupMenu.htm"}
,{"title":"TneTabControl.OnCanFocus","href":"neTabControl.TneTabControl.OnCanFocus.htm"}
,{"title":"TneTabControl.OnChange","href":"neTabControl.TneTabControl.OnChange.htm"}
,{"title":"TneTabControl.OnChangeTab(TObject)","href":"neTabControl.TneTabControl.OnChangeTab.htm"}
,{"title":"TneTabControl.OnClick","href":"neTabControl.TneTabControl.OnClick.htm"}
,{"title":"TneTabControl.OnCloseAllTabs(TObject)","href":"neTabControl.TneTabControl.OnCloseAllTabs.htm"}
,{"title":"TneTabControl.OnCloseHintTimer(TObject)","href":"neTabControl.TneTabControl.OnCloseHintTimer.htm"}
,{"title":"TneTabControl.OnCloseOtherTabs(TObject)","href":"neTabControl.TneTabControl.OnCloseOtherTabs.htm"}
,{"title":"TneTabControl.OnCustomHint","href":"neTabControl.TneTabControl.OnCustomHint.htm"}
,{"title":"TneTabControl.OnDblClick","href":"neTabControl.TneTabControl.OnDblClick.htm"}
,{"title":"TneTabControl.OnDragDrop","href":"neTabControl.TneTabControl.OnDragDrop.htm"}
,{"title":"TneTabControl.OnDragEnd","href":"neTabControl.TneTabControl.OnDragEnd.htm"}
,{"title":"TneTabControl.OnDragEnter","href":"neTabControl.TneTabControl.OnDragEnter.htm"}
,{"title":"TneTabControl.OnDragLeave","href":"neTabControl.TneTabControl.OnDragLeave.htm"}
,{"title":"TneTabControl.OnDragOver","href":"neTabControl.TneTabControl.OnDragOver.htm"}
,{"title":"TneTabControl.OnEnter","href":"neTabControl.TneTabControl.OnEnter.htm"}
,{"title":"TneTabControl.OnExit","href":"neTabControl.TneTabControl.OnExit.htm"}
,{"title":"TneTabControl.OnInternalTimer(TObject)","href":"neTabControl.TneTabControl.OnInternalTimer.htm"}
,{"title":"TneTabControl.OnKeyDown","href":"neTabControl.TneTabControl.OnKeyDown.htm"}
,{"title":"TneTabControl.OnKeyUp","href":"neTabControl.TneTabControl.OnKeyUp.htm"}
,{"title":"TneTabControl.OnMainBarChange(TObject)","href":"neTabControl.TneTabControl.OnMainBarChange.htm"}
,{"title":"TneTabControl.OnMouseDown","href":"neTabControl.TneTabControl.OnMouseDown.htm"}
,{"title":"TneTabControl.OnMouseEnter","href":"neTabControl.TneTabControl.OnMouseEnter.htm"}
,{"title":"TneTabControl.OnMouseEnterToMainControl(TObject)","href":"neTabControl.TneTabControl.OnMouseEnterToMainControl.htm"}
,{"title":"TneTabControl.OnMouseLeave","href":"neTabControl.TneTabControl.OnMouseLeave.htm"}
,{"title":"TneTabControl.OnMouseMove","href":"neTabControl.TneTabControl.OnMouseMove.htm"}
,{"title":"TneTabControl.OnMouseUp","href":"neTabControl.TneTabControl.OnMouseUp.htm"}
,{"title":"TneTabControl.OnMouseWheel","href":"neTabControl.TneTabControl.OnMouseWheel.htm"}
,{"title":"TneTabControl.OnPaint","href":"neTabControl.TneTabControl.OnPaint.htm"}
,{"title":"TneTabControl.OnPainting","href":"neTabControl.TneTabControl.OnPainting.htm"}
,{"title":"TneTabControl.OnResize","href":"neTabControl.TneTabControl.OnResize.htm"}
,{"title":"TneTabControl.OnSelectTabInPopupMenu(TObject)","href":"neTabControl.TneTabControl.OnSelectTabInPopupMenu.htm"}
,{"title":"TneTabControl.OnTabBarChange(TObject)","href":"neTabControl.TneTabControl.OnTabBarChange.htm"}
,{"title":"TneTabControl.Opacity","href":"neTabControl.TneTabControl.Opacity.htm"}
,{"title":"TneTabControl.Padding","href":"neTabControl.TneTabControl.Padding.htm"}
,{"title":"TneTabControl.PopupMenu","href":"neTabControl.TneTabControl.PopupMenu.htm"}
,{"title":"TneTabControl.Position","href":"neTabControl.TneTabControl.Position.htm"}
,{"title":"TneTabControl.RefreshControl(string)","href":"neTabControl.TneTabControl.RefreshControl(string).htm"}
,{"title":"TneTabControl.RefreshTabHeight(string)","href":"neTabControl.TneTabControl.RefreshTabHeight(string).htm"}
,{"title":"TneTabControl.RotationAngle","href":"neTabControl.TneTabControl.RotationAngle.htm"}
,{"title":"TneTabControl.RotationCenter","href":"neTabControl.TneTabControl.RotationCenter.htm"}
,{"title":"TneTabControl.SaveTabs(TExportElements,TSetOfStrings,TStringList)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"TneTabControl.Scale","href":"neTabControl.TneTabControl.Scale.htm"}
,{"title":"TneTabControl.SetActiveTab(TneTabItem)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
,{"title":"TneTabControl.SetActiveTag(string)","href":"neTabControl.TneTabControl.SetActiveTag.htm"}
,{"title":"TneTabControl.SetHintInterval(Cardinal)","href":"neTabControl.TneTabControl.SetHintInterval.htm"}
,{"title":"TneTabControl.setTabAnimation(TShowTabAnimation)","href":"neTabControl.TneTabControl.setTabAnimation.htm"}
,{"title":"TneTabControl.setTabAnimationDuration(double)","href":"neTabControl.TneTabControl.setTabAnimationDuration.htm"}
,{"title":"TneTabControl.SetTabAnimationInterpolation(TInterpolationType)","href":"neTabControl.TneTabControl.SetTabAnimationInterpolation.htm"}
,{"title":"TneTabControl.setTabAnimationType(TAnimationType)","href":"neTabControl.TneTabControl.setTabAnimationType.htm"}
,{"title":"TneTabControl.SetTabHeight(Integer)","href":"neTabControl.TneTabControl.SetTabHeight.htm"}
,{"title":"TneTabControl.SetTabOrientation(TneTabOrientation)","href":"neTabControl.TneTabControl.SetTabOrientation.htm"}
,{"title":"TneTabControl.SetTabPosition(TTabPosition)","href":"neTabControl.TneTabControl.SetTabPosition.htm"}
,{"title":"TneTabControl.ShowHint(string,TPointF)","href":"neTabControl.TneTabControl.ShowHint.htm"}
,{"title":"TneTabControl.ShowPopupMenu(INotification)","href":"neTabControl.TneTabControl.ShowPopupMenu.htm"}
,{"title":"TneTabControl.Size","href":"neTabControl.TneTabControl.Size.htm"}
,{"title":"TneTabControl.StyleLookup","href":"neTabControl.TneTabControl.StyleLookup.htm"}
,{"title":"TneTabControl.TabAnimation","href":"neTabControl.TneTabControl.TabAnimation.htm"}
,{"title":"TneTabControl.TabAnimationDuration","href":"neTabControl.TneTabControl.TabAnimationDuration.htm"}
,{"title":"TneTabControl.TabAnimationInterpolation","href":"neTabControl.TneTabControl.TabAnimationInterpolation.htm"}
,{"title":"TneTabControl.TabAnimationType","href":"neTabControl.TneTabControl.TabAnimationType.htm"}
,{"title":"TneTabControl.TabCount","href":"neTabControl.TneTabControl.TabCount.htm"}
,{"title":"TneTabControl.TabHeight","href":"neTabControl.TneTabControl.TabHeight.htm"}
,{"title":"TneTabControl.TabOrder","href":"neTabControl.TneTabControl.TabOrder.htm"}
,{"title":"TneTabControl.TabOrientation","href":"neTabControl.TneTabControl.TabOrientation.htm"}
,{"title":"TneTabControl.TabPosition","href":"neTabControl.TneTabControl.TabPosition.htm"}
,{"title":"TneTabControl.Tabs[Integer]","href":"neTabControl.TneTabControl.Tabs[Integer].htm"}
,{"title":"TneTabControl.ToggleVisible(Boolean,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.ToggleVisible.htm"}
,{"title":"TneTabControl.Transition","href":"neTabControl.TneTabControl.Transition.htm"}
,{"title":"TneTabControl.UpdateFromProvider(INotification)","href":"neTabControl.TneTabControl.UpdateFromProvider.htm"}
,{"title":"TneTabControl.UpdatePosition","href":"neTabControl.TneTabControl.UpdatePosition.htm"}
,{"title":"TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"TneTabControl.Visible","href":"neTabControl.TneTabControl.Visible.htm"}
,{"title":"TneTabControl.Width","href":"neTabControl.TneTabControl.Width.htm"}
,{"title":"TneTabItem","href":"neTabItem.TneTabItem.htm"}
,{"title":"TneTabItem.ApplyStyle","href":"neTabItem.TneTabItem.ApplyStyle.htm"}
,{"title":"TneTabItem.CanClose","href":"neTabItem.TneTabItem.CanClose.htm"}
,{"title":"TneTabItem.Caption","href":"neTabItem.TneTabItem.Caption.htm"}
,{"title":"TneTabItem.CaptionAlignment","href":"neTabItem.TneTabItem.CaptionAlignment.htm"}
,{"title":"TneTabItem.CloseAlignment","href":"neTabItem.TneTabItem.CloseAlignment.htm"}
,{"title":"TneTabItem.CloseImageHover","href":"neTabItem.TneTabItem.CloseImageHover.htm"}
,{"title":"TneTabItem.CloseImageNormal","href":"neTabItem.TneTabItem.CloseImageNormal.htm"}
,{"title":"TneTabItem.CloseImagePressed","href":"neTabItem.TneTabItem.CloseImagePressed.htm"}
,{"title":"TneTabItem.CloseMenuItem(TObject)","href":"neTabItem.TneTabItem.CloseMenuItem.htm"}
,{"title":"TneTabItem.ControlAlignment","href":"neTabItem.TneTabItem.ControlAlignment.htm"}
,{"title":"TneTabItem.ControlToShow","href":"neTabItem.TneTabItem.ControlToShow.htm"}
,{"title":"TneTabItem.Create(TComponent)","href":"neTabItem.TneTabItem.Create.htm"}
,{"title":"TneTabItem.Destroy","href":"neTabItem.TneTabItem.Destroy.htm"}
,{"title":"TneTabItem.DoMouseLeave","href":"neTabItem.TneTabItem.DoMouseLeave.htm"}
,{"title":"TneTabItem.fCanClose","href":"neTabItem.TneTabItem.fCanClose.htm"}
,{"title":"TneTabItem.fCaption","href":"neTabItem.TneTabItem.fCaption.htm"}
,{"title":"TneTabItem.fCaptionAlignment","href":"neTabItem.TneTabItem.fCaptionAlignment.htm"}
,{"title":"TneTabItem.fCloseAlignment","href":"neTabItem.TneTabItem.fCloseAlignment.htm"}
,{"title":"TneTabItem.fCloseImages","href":"neTabItem.TneTabItem.fCloseImages.htm"}
,{"title":"TneTabItem.fCloseImageToShow","href":"neTabItem.TneTabItem.fCloseImageToShow.htm"}
,{"title":"TneTabItem.fControlAlignment","href":"neTabItem.TneTabItem.fControlAlignment.htm"}
,{"title":"TneTabItem.fControlToShow","href":"neTabItem.TneTabItem.fControlToShow.htm"}
,{"title":"TneTabItem.fHintInterval","href":"neTabItem.TneTabItem.fHintInterval.htm"}
,{"title":"TneTabItem.fHintText","href":"neTabItem.TneTabItem.fHintText.htm"}
,{"title":"TneTabItem.fHintTimer","href":"neTabItem.TneTabItem.fHintTimer.htm"}
,{"title":"TneTabItem.fInternalTimer","href":"neTabItem.TneTabItem.fInternalTimer.htm"}
,{"title":"TneTabItem.fLastMousePoint","href":"neTabItem.TneTabItem.fLastMousePoint.htm"}
,{"title":"TneTabItem.fMaxTabWidth","href":"neTabItem.TneTabItem.fMaxTabWidth.htm"}
,{"title":"TneTabItem.fMinTabWidth","href":"neTabItem.TneTabItem.fMinTabWidth.htm"}
,{"title":"TneTabItem.fMouseState","href":"neTabItem.TneTabItem.fMouseState.htm"}
,{"title":"TneTabItem.fPopupMenuAfterDefault","href":"neTabItem.TneTabItem.fPopupMenuAfterDefault.htm"}
,{"title":"TneTabItem.fPopupMenuBeforeDefault","href":"neTabItem.TneTabItem.fPopupMenuBeforeDefault.htm"}
,{"title":"TneTabItem.fProvider","href":"neTabItem.TneTabItem.fProvider.htm"}
,{"title":"TneTabItem.fRefreshCloseImage","href":"neTabItem.TneTabItem.fRefreshCloseImage.htm"}
,{"title":"TneTabItem.fShowControl","href":"neTabItem.TneTabItem.fShowControl.htm"}
,{"title":"TneTabItem.fShowPopupMenu","href":"neTabItem.TneTabItem.fShowPopupMenu.htm"}
,{"title":"TneTabItem.fSubscriber","href":"neTabItem.TneTabItem.fSubscriber.htm"}
,{"title":"TneTabItem.fTabTag","href":"neTabItem.TneTabItem.fTabTag.htm"}
,{"title":"TneTabItem.fTabWidth","href":"neTabItem.TneTabItem.fTabWidth.htm"}
,{"title":"TneTabItem.GetCloseImage(TCloseImagesType)","href":"neTabItem.TneTabItem.GetCloseImage.htm"}
,{"title":"TneTabItem.GetTabWidth","href":"neTabItem.TneTabItem.GetTabWidth.htm"}
,{"title":"TneTabItem.HintInterval","href":"neTabItem.TneTabItem.HintInterval.htm"}
,{"title":"TneTabItem.HintText","href":"neTabItem.TneTabItem.HintText.htm"}
,{"title":"TneTabItem.MaxTabWidth","href":"neTabItem.TneTabItem.MaxTabWidth.htm"}
,{"title":"TneTabItem.MinTabWidth","href":"neTabItem.TneTabItem.MinTabWidth.htm"}
,{"title":"TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseClick.htm"}
,{"title":"TneTabItem.MouseMove(TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseMove.htm"}
,{"title":"TneTabItem.NotifyToDeleteTab","href":"neTabItem.TneTabItem.NotifyToDeleteTab.htm"}
,{"title":"TneTabItem.OnHintTimer(TObject)","href":"neTabItem.TneTabItem.OnHintTimer.htm"}
,{"title":"TneTabItem.OnInternalTimer(TObject)","href":"neTabItem.TneTabItem.OnInternalTimer.htm"}
,{"title":"TneTabItem.PopupMenuAfterDefault","href":"neTabItem.TneTabItem.PopupMenuAfterDefault.htm"}
,{"title":"TneTabItem.PopupMenuBeforeDefault","href":"neTabItem.TneTabItem.PopupMenuBeforeDefault.htm"}
,{"title":"TneTabItem.Provider","href":"neTabItem.TneTabItem.Provider.htm"}
,{"title":"TneTabItem.RefreshControl","href":"neTabItem.TneTabItem.RefreshControl.htm"}
,{"title":"TneTabItem.SafeApplyStyle","href":"neTabItem.TneTabItem.SafeApplyStyle.htm"}
,{"title":"TneTabItem.SetCanClose(Boolean)","href":"neTabItem.TneTabItem.SetCanClose.htm"}
,{"title":"TneTabItem.SetCaption(TLabel)","href":"neTabItem.TneTabItem.SetCaption.htm"}
,{"title":"TneTabItem.SetCaptionAlignment(TAlignLayout)","href":"neTabItem.TneTabItem.SetCaptionAlignment.htm"}
,{"title":"TneTabItem.SetCloseAlignment(TalignLayout)","href":"neTabItem.TneTabItem.SetCloseAlignment.htm"}
,{"title":"TneTabItem.SetCloseImage(TCloseImagesType,TBitmap)","href":"neTabItem.TneTabItem.SetCloseImage.htm"}
,{"title":"TneTabItem.SetControlAlignment(TAlignLayout)","href":"neTabItem.TneTabItem.SetControlAlignment.htm"}
,{"title":"TneTabItem.SetControlToShow(TControl)","href":"neTabItem.TneTabItem.SetControlToShow.htm"}
,{"title":"TneTabItem.SetMaxTabWidth(single)","href":"neTabItem.TneTabItem.SetMaxTabWidth.htm"}
,{"title":"TneTabItem.SetMinTabWidth(single)","href":"neTabItem.TneTabItem.SetMinTabWidth.htm"}
,{"title":"TneTabItem.SetShowControl(Boolean)","href":"neTabItem.TneTabItem.SetShowControl.htm"}
,{"title":"TneTabItem.SetTabWidth(single)","href":"neTabItem.TneTabItem.SetTabWidth.htm"}
,{"title":"TneTabItem.SetWidth(Single)","href":"neTabItem.TneTabItem.SetWidth.htm"}
,{"title":"TneTabItem.ShowControl","href":"neTabItem.TneTabItem.ShowControl.htm"}
,{"title":"TneTabItem.ShowFullPopupMenu(TObject,Single,Single)","href":"neTabItem.TneTabItem.ShowFullPopupMenu.htm"}
,{"title":"TneTabItem.ShowPopupMenu","href":"neTabItem.TneTabItem.ShowPopupMenu.htm"}
,{"title":"TneTabItem.TabTag","href":"neTabItem.TneTabItem.TabTag.htm"}
,{"title":"TneTabItem.TabWidth","href":"neTabItem.TneTabItem.TabWidth.htm"}
,{"title":"TneTabItem.UpdateFromProvider(INotification)","href":"neTabItem.TneTabItem.UpdateFromProvider.htm"}
,{"title":"TneTabOrientation","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"TneTabOrientation.orBottom","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"TneTabOrientation.orLeft","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"TneTabOrientation.orRight","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"TneTabOrientation.orTop","href":"neTabControl.TneTabOrientation.htm"}
,{"title":"TneTimer","href":"neTabTypes.TneTimer.htm"}
,{"title":"TneTimer.Action","href":"neTabTypes.TneTimer.Action.htm"}
,{"title":"TneTimer.Value","href":"neTabTypes.TneTimer.Value.htm"}
,{"title":"TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"TOnAfterCloseAllItems","href":"neTabControl.TOnAfterCloseAllItems.htm"}
,{"title":"TOnAfterCloseOtherItems","href":"neTabControl.TOnAfterCloseOtherItems.htm"}
,{"title":"TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"TOnBeforeCloseAllItems","href":"neTabControl.TOnBeforeCloseAllItems.htm"}
,{"title":"TOnBeforeCloseOtherItems","href":"neTabControl.TOnBeforeCloseOtherItems.htm"}
,{"title":"TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"TOnCustomHint","href":"neTabControl.TOnCustomHint.htm"}
,{"title":"TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
,{"title":"TShowTabAnimation","href":"neTabTypes.TShowTabAnimation.htm"}
,{"title":"TShowTabAnimation.taFade","href":"neTabTypes.TShowTabAnimation.htm"}
,{"title":"TShowTabAnimation.taNone","href":"neTabTypes.TShowTabAnimation.htm"}
]