[{"title":"NETabControlPackage","key":"NETabControlPackage","href":"NETabControlPackage.htm","activate":true,"children":[{"title":"neTabControl","key":"neTabControl","href":"neTabControl.htm","children":[{"title":"Classes","key":"neTabControl_Classes","href":"neTabControl_Classes.htm","children":[{"title":"TneTabControl","key":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabControl_Constructors","href":"neTabControl.TneTabControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"Destroy","key":"neTabControl.TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabControl_Properties","href":"neTabControl.TneTabControl_Properties.htm","children":[{"title":"CloseImageHover","key":"neTabControl.TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"CloseTabLabel","key":"neTabControl.TneTabControl.CloseTabLabel","href":"neTabControl.TneTabControl.CloseTabLabel.htm"}
,{"title":"HintStyle","key":"neTabControl.TneTabControl.HintStyle","href":"neTabControl.TneTabControl.HintStyle.htm"}
,{"title":"MaxTabWidth","key":"neTabControl.TneTabControl.MaxTabWidth","href":"neTabControl.TneTabControl.MaxTabWidth.htm"}
,{"title":"PopupAfterDefault","key":"neTabControl.TneTabControl.PopupAfterDefault","href":"neTabControl.TneTabControl.PopupAfterDefault.htm"}
,{"title":"PopupBeforeDefault","key":"neTabControl.TneTabControl.PopupBeforeDefault","href":"neTabControl.TneTabControl.PopupBeforeDefault.htm"}
,{"title":"Version","key":"neTabControl.TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabControl_Methods","href":"neTabControl.TneTabControl_Methods.htm","children":[{"title":"AddTab(string,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string%2CTFrame).htm"}
,{"title":"AddTab(string,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string%2CTneTabItem%2CTFrame).htm"}
,{"title":"DeleteTab(string)","key":"neTabControl.TneTabControl.DeleteTab(string)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"FindTabOrderFromTag(string)","key":"neTabControl.TneTabControl.FindTabOrderFromTag(string)","href":"neTabControl.TneTabControl.FindTabOrderFromTag.htm"}
,{"title":"GetFrame(string)","key":"neTabControl.TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"GetTab(string)","key":"neTabControl.TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"GetTabsTags","key":"neTabControl.TneTabControl.GetTabsTags","href":"neTabControl.TneTabControl.GetTabsTags.htm"}
,{"title":"GetTabsText","key":"neTabControl.TneTabControl.GetTabsText","href":"neTabControl.TneTabControl.GetTabsText.htm"}
,{"title":"InsertTab(string,Integer,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,Integer,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTFrame).htm"}
,{"title":"InsertTab(string,Integer,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,Integer,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTneTabItem%2CTFrame).htm"}
,{"title":"SetActiveTab(string)","key":"neTabControl.TneTabControl.SetActiveTab(string)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
]}
,{"title":"Events","key":"neTabControl.TneTabControl_Events","href":"neTabControl.TneTabControl_Events.htm","children":[{"title":"OnAfterDelete","key":"neTabControl.TneTabControl.OnAfterDelete","href":"neTabControl.TneTabControl.OnAfterDelete.htm"}
,{"title":"OnBeforeDelete","key":"neTabControl.TneTabControl.OnBeforeDelete","href":"neTabControl.TneTabControl.OnBeforeDelete.htm"}
]}
]}
,{"title":"TneTabItem","key":"neTabControl.TneTabItem","href":"neTabControl.TneTabItem.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabItem_Constructors","href":"neTabControl.TneTabItem_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabItem.Create(TComponent)","href":"neTabControl.TneTabItem.Create.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabItem_Properties","href":"neTabControl.TneTabItem_Properties.htm","children":[{"title":"CanClose","key":"neTabControl.TneTabItem.CanClose","href":"neTabControl.TneTabItem.CanClose.htm"}
,{"title":"CloseImageHover","key":"neTabControl.TneTabItem.CloseImageHover","href":"neTabControl.TneTabItem.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabItem.CloseImageNormal","href":"neTabControl.TneTabItem.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabItem.CloseImagePressed","href":"neTabControl.TneTabItem.CloseImagePressed.htm"}
,{"title":"Deleted","key":"neTabControl.TneTabItem.Deleted","href":"neTabControl.TneTabItem.Deleted.htm"}
,{"title":"Icon","key":"neTabControl.TneTabItem.Icon","href":"neTabControl.TneTabItem.Icon.htm"}
,{"title":"ShowIcon","key":"neTabControl.TneTabItem.ShowIcon","href":"neTabControl.TneTabItem.ShowIcon.htm"}
,{"title":"Version","key":"neTabControl.TneTabItem.Version","href":"neTabControl.TneTabItem.Version.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabItem_Methods","href":"neTabControl.TneTabItem_Methods.htm","children":[{"title":"ApplyStyle","key":"neTabControl.TneTabItem.ApplyStyle","href":"neTabControl.TneTabItem.ApplyStyle.htm"}
,{"title":"MouseClick(TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseClick.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabControl_Enumerations","href":"neTabControl_Enumerations.htm","children":[{"title":"THintStyle","key":"neTabControl.THintStyle","href":"neTabControl.THintStyle.htm"}
]}
,{"title":"Delegates","key":"neTabControl_Delegates","href":"neTabControl_Delegates.htm","children":[{"title":"TOnAfterDelete","key":"neTabControl.TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"TOnBeforeDelete","key":"neTabControl.TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
]}
,{"title":"Constants","key":"neTabControl_Constants","href":"neTabControl_Constants.htm","children":[{"title":"BugVersion","key":"neTabControl.BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabControl.MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabControl.MinorVersion","href":"neTabControl.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabControl_Routines","href":"neTabControl_Routines.htm","children":[{"title":"Register","key":"neTabControl.Register","href":"neTabControl.Register.htm"}
,{"title":"ResizeBitmap(TBitmap,Integer,Integer)","key":"neTabControl.ResizeBitmap(TBitmap,Integer,Integer)","href":"neTabControl.ResizeBitmap.htm"}
]}
]}
]}
]