[{"title":"neTabControlPackage","key":"neTabControlPackage","href":"neTabControlPackage.htm","activate":true,"children":[{"title":"neTabControl","key":"neTabControl","href":"neTabControl.htm","children":[{"title":"Classes","key":"neTabControl_Classes","href":"neTabControl_Classes.htm","children":[{"title":"TneTabControl","key":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabControl_Constructors","href":"neTabControl.TneTabControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"Destroy","key":"neTabControl.TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabControl_Properties","href":"neTabControl.TneTabControl_Properties.htm","children":[{"title":"ActiveTab","key":"neTabControl.TneTabControl.ActiveTab","href":"neTabControl.TneTabControl.ActiveTab.htm"}
,{"title":"ActiveTag","key":"neTabControl.TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"Align","key":"neTabControl.TneTabControl.Align","href":"neTabControl.TneTabControl.Align.htm"}
,{"title":"Anchors","key":"neTabControl.TneTabControl.Anchors","href":"neTabControl.TneTabControl.Anchors.htm"}
,{"title":"CanParentFocus","key":"neTabControl.TneTabControl.CanParentFocus","href":"neTabControl.TneTabControl.CanParentFocus.htm"}
,{"title":"ClipChildren","key":"neTabControl.TneTabControl.ClipChildren","href":"neTabControl.TneTabControl.ClipChildren.htm"}
,{"title":"ClipParent","key":"neTabControl.TneTabControl.ClipParent","href":"neTabControl.TneTabControl.ClipParent.htm"}
,{"title":"CloseAllOtherTabsText","key":"neTabControl.TneTabControl.CloseAllOtherTabsText","href":"neTabControl.TneTabControl.CloseAllOtherTabsText.htm"}
,{"title":"CloseAllTabsText","key":"neTabControl.TneTabControl.CloseAllTabsText","href":"neTabControl.TneTabControl.CloseAllTabsText.htm"}
,{"title":"CloseImageHover","key":"neTabControl.TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"CloseTabText","key":"neTabControl.TneTabControl.CloseTabText","href":"neTabControl.TneTabControl.CloseTabText.htm"}
,{"title":"Cursor","key":"neTabControl.TneTabControl.Cursor","href":"neTabControl.TneTabControl.Cursor.htm"}
,{"title":"DisableFocusEffect","key":"neTabControl.TneTabControl.DisableFocusEffect","href":"neTabControl.TneTabControl.DisableFocusEffect.htm"}
,{"title":"DragMode","key":"neTabControl.TneTabControl.DragMode","href":"neTabControl.TneTabControl.DragMode.htm"}
,{"title":"Enabled","key":"neTabControl.TneTabControl.Enabled","href":"neTabControl.TneTabControl.Enabled.htm"}
,{"title":"EnableDragHighlight","key":"neTabControl.TneTabControl.EnableDragHighlight","href":"neTabControl.TneTabControl.EnableDragHighlight.htm"}
,{"title":"Height","key":"neTabControl.TneTabControl.Height","href":"neTabControl.TneTabControl.Height.htm"}
,{"title":"HintInterval","key":"neTabControl.TneTabControl.HintInterval","href":"neTabControl.TneTabControl.HintInterval.htm"}
,{"title":"HintType","key":"neTabControl.TneTabControl.HintType","href":"neTabControl.TneTabControl.HintType.htm"}
,{"title":"HitTest","key":"neTabControl.TneTabControl.HitTest","href":"neTabControl.TneTabControl.HitTest.htm"}
,{"title":"Locked","key":"neTabControl.TneTabControl.Locked","href":"neTabControl.TneTabControl.Locked.htm"}
,{"title":"Margins","key":"neTabControl.TneTabControl.Margins","href":"neTabControl.TneTabControl.Margins.htm"}
,{"title":"OnApplyStyleLookup","key":"neTabControl.TneTabControl.OnApplyStyleLookup","href":"neTabControl.TneTabControl.OnApplyStyleLookup.htm"}
,{"title":"OnCanFocus","key":"neTabControl.TneTabControl.OnCanFocus","href":"neTabControl.TneTabControl.OnCanFocus.htm"}
,{"title":"OnChange","key":"neTabControl.TneTabControl.OnChange","href":"neTabControl.TneTabControl.OnChange.htm"}
,{"title":"OnClick","key":"neTabControl.TneTabControl.OnClick","href":"neTabControl.TneTabControl.OnClick.htm"}
,{"title":"OnDblClick","key":"neTabControl.TneTabControl.OnDblClick","href":"neTabControl.TneTabControl.OnDblClick.htm"}
,{"title":"OnDragDrop","key":"neTabControl.TneTabControl.OnDragDrop","href":"neTabControl.TneTabControl.OnDragDrop.htm"}
,{"title":"OnDragEnd","key":"neTabControl.TneTabControl.OnDragEnd","href":"neTabControl.TneTabControl.OnDragEnd.htm"}
,{"title":"OnDragEnter","key":"neTabControl.TneTabControl.OnDragEnter","href":"neTabControl.TneTabControl.OnDragEnter.htm"}
,{"title":"OnDragLeave","key":"neTabControl.TneTabControl.OnDragLeave","href":"neTabControl.TneTabControl.OnDragLeave.htm"}
,{"title":"OnDragOver","key":"neTabControl.TneTabControl.OnDragOver","href":"neTabControl.TneTabControl.OnDragOver.htm"}
,{"title":"OnEnter","key":"neTabControl.TneTabControl.OnEnter","href":"neTabControl.TneTabControl.OnEnter.htm"}
,{"title":"OnExit","key":"neTabControl.TneTabControl.OnExit","href":"neTabControl.TneTabControl.OnExit.htm"}
,{"title":"OnKeyDown","key":"neTabControl.TneTabControl.OnKeyDown","href":"neTabControl.TneTabControl.OnKeyDown.htm"}
,{"title":"OnKeyUp","key":"neTabControl.TneTabControl.OnKeyUp","href":"neTabControl.TneTabControl.OnKeyUp.htm"}
,{"title":"OnMouseDown","key":"neTabControl.TneTabControl.OnMouseDown","href":"neTabControl.TneTabControl.OnMouseDown.htm"}
,{"title":"OnMouseEnter","key":"neTabControl.TneTabControl.OnMouseEnter","href":"neTabControl.TneTabControl.OnMouseEnter.htm"}
,{"title":"OnMouseLeave","key":"neTabControl.TneTabControl.OnMouseLeave","href":"neTabControl.TneTabControl.OnMouseLeave.htm"}
,{"title":"OnMouseMove","key":"neTabControl.TneTabControl.OnMouseMove","href":"neTabControl.TneTabControl.OnMouseMove.htm"}
,{"title":"OnMouseUp","key":"neTabControl.TneTabControl.OnMouseUp","href":"neTabControl.TneTabControl.OnMouseUp.htm"}
,{"title":"OnMouseWheel","key":"neTabControl.TneTabControl.OnMouseWheel","href":"neTabControl.TneTabControl.OnMouseWheel.htm"}
,{"title":"OnPaint","key":"neTabControl.TneTabControl.OnPaint","href":"neTabControl.TneTabControl.OnPaint.htm"}
,{"title":"OnPainting","key":"neTabControl.TneTabControl.OnPainting","href":"neTabControl.TneTabControl.OnPainting.htm"}
,{"title":"OnResize","key":"neTabControl.TneTabControl.OnResize","href":"neTabControl.TneTabControl.OnResize.htm"}
,{"title":"Opacity","key":"neTabControl.TneTabControl.Opacity","href":"neTabControl.TneTabControl.Opacity.htm"}
,{"title":"Padding","key":"neTabControl.TneTabControl.Padding","href":"neTabControl.TneTabControl.Padding.htm"}
,{"title":"PopupMenu","key":"neTabControl.TneTabControl.PopupMenu","href":"neTabControl.TneTabControl.PopupMenu.htm"}
,{"title":"Position","key":"neTabControl.TneTabControl.Position","href":"neTabControl.TneTabControl.Position.htm"}
,{"title":"RotationAngle","key":"neTabControl.TneTabControl.RotationAngle","href":"neTabControl.TneTabControl.RotationAngle.htm"}
,{"title":"RotationCenter","key":"neTabControl.TneTabControl.RotationCenter","href":"neTabControl.TneTabControl.RotationCenter.htm"}
,{"title":"Scale","key":"neTabControl.TneTabControl.Scale","href":"neTabControl.TneTabControl.Scale.htm"}
,{"title":"Size","key":"neTabControl.TneTabControl.Size","href":"neTabControl.TneTabControl.Size.htm"}
,{"title":"StyleLookup","key":"neTabControl.TneTabControl.StyleLookup","href":"neTabControl.TneTabControl.StyleLookup.htm"}
,{"title":"TabCount","key":"neTabControl.TneTabControl.TabCount","href":"neTabControl.TneTabControl.TabCount.htm"}
,{"title":"TabHeight","key":"neTabControl.TneTabControl.TabHeight","href":"neTabControl.TneTabControl.TabHeight.htm"}
,{"title":"TabOrder","key":"neTabControl.TneTabControl.TabOrder","href":"neTabControl.TneTabControl.TabOrder.htm"}
,{"title":"TabOrientation","key":"neTabControl.TneTabControl.TabOrientation","href":"neTabControl.TneTabControl.TabOrientation.htm"}
,{"title":"TabPosition","key":"neTabControl.TneTabControl.TabPosition","href":"neTabControl.TneTabControl.TabPosition.htm"}
,{"title":"Tabs[Integer]","key":"neTabControl.TneTabControl.Tabs(Integer)","href":"neTabControl.TneTabControl.Tabs[Integer].htm"}
,{"title":"Transition","key":"neTabControl.TneTabControl.Transition","href":"neTabControl.TneTabControl.Transition.htm"}
,{"title":"Version","key":"neTabControl.TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"Visible","key":"neTabControl.TneTabControl.Visible","href":"neTabControl.TneTabControl.Visible.htm"}
,{"title":"Width","key":"neTabControl.TneTabControl.Width","href":"neTabControl.TneTabControl.Width.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabControl_Methods","href":"neTabControl.TneTabControl_Methods.htm","children":[{"title":"AddSidebarControl(TControl,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.AddSidebarControl(TControl,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.AddSidebarControl.htm"}
,{"title":"AddTab(string)","key":"neTabControl.TneTabControl.AddTab(string)","href":"neTabControl.TneTabControl.AddTab(string).htm"}
,{"title":"AddTab(string,TneTabItem)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem).htm"}
,{"title":"AddTab(string,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem,TFrame).htm"}
,{"title":"DeleteAllTabs(Boolean)","key":"neTabControl.TneTabControl.DeleteAllTabs(Boolean)","href":"neTabControl.TneTabControl.DeleteAllTabs.htm"}
,{"title":"DeleteSidebarControl(Integer,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.DeleteSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.DeleteSidebarControl.htm"}
,{"title":"DeleteTab(string,Boolean)","key":"neTabControl.TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"GetControl(string)","key":"neTabControl.TneTabControl.GetControl(string)","href":"neTabControl.TneTabControl.GetControl.htm"}
,{"title":"GetFrame(string)","key":"neTabControl.TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"GetSidebarControl(Integer,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.GetSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControl.htm"}
,{"title":"GetSidebarControlCount(TneSibebarControlPosition)","key":"neTabControl.TneTabControl.GetSidebarControlCount(TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControlCount.htm"}
,{"title":"GetTab(string)","key":"neTabControl.TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"GetTabItemsList(TList)","key":"neTabControl.TneTabControl.GetTabItemsList(TList@)","href":"neTabControl.TneTabControl.GetTabItemsList.htm"}
,{"title":"GetTag(Integer)","key":"neTabControl.TneTabControl.GetTag(Integer)","href":"neTabControl.TneTabControl.GetTag.htm"}
,{"title":"GetTagList(TStringList)","key":"neTabControl.TneTabControl.GetTagList(TStringList@)","href":"neTabControl.TneTabControl.GetTagList.htm"}
,{"title":"InsertTab(string,integer)","key":"neTabControl.TneTabControl.InsertTab(string,integer)","href":"neTabControl.TneTabControl.InsertTab(string,integer).htm"}
,{"title":"InsertTab(string,integer,TneTabItem)","key":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem@)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem).htm"}
,{"title":"InsertTab(string,integer,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem,TFrame).htm"}
,{"title":"RefreshControl(string)","key":"neTabControl.TneTabControl.RefreshControl(string)","href":"neTabControl.TneTabControl.RefreshControl(string).htm"}
,{"title":"RefreshTabHeight(string)","key":"neTabControl.TneTabControl.RefreshTabHeight(string)","href":"neTabControl.TneTabControl.RefreshTabHeight(string).htm"}
,{"title":"SaveTabs(TExportElements,TSetOfStrings,TStringList)","key":"neTabControl.TneTabControl.SaveTabs(TExportElements,TSetOfStrings,TStringList@)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"ToggleVisible(Boolean,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.ToggleVisible(Boolean,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.ToggleVisible.htm"}
]}
,{"title":"Events","key":"neTabControl.TneTabControl_Events","href":"neTabControl.TneTabControl_Events.htm","children":[{"title":"OnAfterAddItem","key":"neTabControl.TneTabControl.OnAfterAddItem","href":"neTabControl.TneTabControl.OnAfterAddItem.htm"}
,{"title":"OnAfterAddSidebarControl","key":"neTabControl.TneTabControl.OnAfterAddSidebarControl","href":"neTabControl.TneTabControl.OnAfterAddSidebarControl.htm"}
,{"title":"OnAfterCloseAllItems","key":"neTabControl.TneTabControl.OnAfterCloseAllItems","href":"neTabControl.TneTabControl.OnAfterCloseAllItems.htm"}
,{"title":"OnAfterCloseOtherItems","key":"neTabControl.TneTabControl.OnAfterCloseOtherItems","href":"neTabControl.TneTabControl.OnAfterCloseOtherItems.htm"}
,{"title":"OnAfterDeleteItem","key":"neTabControl.TneTabControl.OnAfterDeleteItem","href":"neTabControl.TneTabControl.OnAfterDeleteItem.htm"}
,{"title":"OnAfterDeleteSidebarControl","key":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl.htm"}
,{"title":"OnBeforeAddItem","key":"neTabControl.TneTabControl.OnBeforeAddItem","href":"neTabControl.TneTabControl.OnBeforeAddItem.htm"}
,{"title":"OnBeforeAddSidebarControl","key":"neTabControl.TneTabControl.OnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.OnBeforeAddSidebarControl.htm"}
,{"title":"OnBeforeCloseAllItems","key":"neTabControl.TneTabControl.OnBeforeCloseAllItems","href":"neTabControl.TneTabControl.OnBeforeCloseAllItems.htm"}
,{"title":"OnBeforeCloseOtherItems","key":"neTabControl.TneTabControl.OnBeforeCloseOtherItems","href":"neTabControl.TneTabControl.OnBeforeCloseOtherItems.htm"}
,{"title":"OnBeforeDeleteItem","key":"neTabControl.TneTabControl.OnBeforeDeleteItem","href":"neTabControl.TneTabControl.OnBeforeDeleteItem.htm"}
,{"title":"OnBeforeDeleteSidebarControl","key":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl.htm"}
,{"title":"OnBeforePopupMenu","key":"neTabControl.TneTabControl.OnBeforePopupMenu","href":"neTabControl.TneTabControl.OnBeforePopupMenu.htm"}
,{"title":"OnCustomHint","key":"neTabControl.TneTabControl.OnCustomHint","href":"neTabControl.TneTabControl.OnCustomHint.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabControl_Enumerations","href":"neTabControl_Enumerations.htm","children":[{"title":"TneDoChangeType","key":"neTabControl.TneDoChangeType","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"TneHintType","key":"neTabControl.TneHintType","href":"neTabControl.TneHintType.htm"}
,{"title":"TneSibebarControlPosition","key":"neTabControl.TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneTabOrientation","key":"neTabControl.TneTabOrientation","href":"neTabControl.TneTabOrientation.htm"}
]}
,{"title":"Delegates","key":"neTabControl_Delegates","href":"neTabControl_Delegates.htm","children":[{"title":"TOnAfterAddItem","key":"neTabControl.TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"TOnAfterAddSidebarControl","key":"neTabControl.TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"TOnAfterCloseAllItems","key":"neTabControl.TOnAfterCloseAllItems","href":"neTabControl.TOnAfterCloseAllItems.htm"}
,{"title":"TOnAfterCloseOtherItems","key":"neTabControl.TOnAfterCloseOtherItems","href":"neTabControl.TOnAfterCloseOtherItems.htm"}
,{"title":"TOnAfterDeleteItem","key":"neTabControl.TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"TOnAfterDeleteSidebarControl","key":"neTabControl.TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"TOnBeforeAddItem","key":"neTabControl.TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"TOnBeforeAddSibarControl","key":"neTabControl.TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"TOnBeforeCloseAllItems","key":"neTabControl.TOnBeforeCloseAllItems","href":"neTabControl.TOnBeforeCloseAllItems.htm"}
,{"title":"TOnBeforeCloseOtherItems","key":"neTabControl.TOnBeforeCloseOtherItems","href":"neTabControl.TOnBeforeCloseOtherItems.htm"}
,{"title":"TOnBeforeDeleteItem","key":"neTabControl.TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"TOnBeforeDeleteSidebarControl","key":"neTabControl.TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"TOnBeforePopupMenu","key":"neTabControl.TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"TOnCustomHint","key":"neTabControl.TOnCustomHint","href":"neTabControl.TOnCustomHint.htm"}
]}
,{"title":"Constants","key":"neTabControl_Constants","href":"neTabControl_Constants.htm","children":[{"title":"BugVersion","key":"neTabControl.BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabControl.MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabControl.MinorVersion","href":"neTabControl.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabControl_Routines","href":"neTabControl_Routines.htm","children":[{"title":"GetTabControl(TClass)","key":"neTabControl.GetTabControl(TClass)","href":"neTabControl.GetTabControl.htm"}
,{"title":"Register","key":"neTabControl.Register","href":"neTabControl.Register.htm"}
]}
]}
,{"title":"neTabGeneralUtils","key":"neTabGeneralUtils","href":"neTabGeneralUtils.htm","children":[{"title":"Constants","key":"neTabGeneralUtils_Constants","href":"neTabGeneralUtils_Constants.htm","children":[{"title":"BugVersion","key":"neTabGeneralUtils.BugVersion","href":"neTabGeneralUtils.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabGeneralUtils.MajorVersion","href":"neTabGeneralUtils.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabGeneralUtils.MinorVersion","href":"neTabGeneralUtils.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabGeneralUtils_Routines","href":"neTabGeneralUtils_Routines.htm","children":[{"title":"FindParentForm(TFmxObject)","key":"neTabGeneralUtils.FindParentForm(TFmxObject)","href":"neTabGeneralUtils.FindParentForm.htm"}
,{"title":"LoadImageFromResources(string,TBitmap)","key":"neTabGeneralUtils.LoadImageFromResources(string,TBitmap@)","href":"neTabGeneralUtils.LoadImageFromResources.htm"}
]}
]}
,{"title":"neTabItem","key":"neTabItem","href":"neTabItem.htm","children":[{"title":"Classes","key":"neTabItem_Classes","href":"neTabItem_Classes.htm","children":[{"title":"TneCloseImageControl","key":"neTabItem.TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm","children":[{"title":"Constructors","key":"neTabItem.TneCloseImageControl_Constructors","href":"neTabItem.TneCloseImageControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabItem.TneCloseImageControl.Create(TComponent)","href":"neTabItem.TneCloseImageControl.Create.htm"}
,{"title":"Destroy","key":"neTabItem.TneCloseImageControl.Destroy","href":"neTabItem.TneCloseImageControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabItem.TneCloseImageControl_Properties","href":"neTabItem.TneCloseImageControl_Properties.htm","children":[{"title":"CloseImage","key":"neTabItem.TneCloseImageControl.CloseImage","href":"neTabItem.TneCloseImageControl.CloseImage.htm"}
]}
,{"title":"Methods","key":"neTabItem.TneCloseImageControl_Methods","href":"neTabItem.TneCloseImageControl_Methods.htm","children":[{"title":"DoMouseEnter","key":"neTabItem.TneCloseImageControl.DoMouseEnter","href":"neTabItem.TneCloseImageControl.DoMouseEnter.htm"}
,{"title":"DoMouseLeave","key":"neTabItem.TneCloseImageControl.DoMouseLeave","href":"neTabItem.TneCloseImageControl.DoMouseLeave.htm"}
,{"title":"MouseDown(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneCloseImageControl.MouseDown(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseDown.htm"}
,{"title":"MouseUp(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneCloseImageControl.MouseUp(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseUp.htm"}
,{"title":"SetCloseImage(TBitmap)","key":"neTabItem.TneCloseImageControl.SetCloseImage(TBitmap)","href":"neTabItem.TneCloseImageControl.SetCloseImage.htm"}
]}
]}
,{"title":"TneControl","key":"neTabItem.TneControl","href":"neTabItem.TneControl.htm","children":[{"title":"Properties","key":"neTabItem.TneControl_Properties","href":"neTabItem.TneControl_Properties.htm","children":[{"title":"InnerControl","key":"neTabItem.TneControl.InnerControl","href":"neTabItem.TneControl.InnerControl.htm"}
]}
]}
,{"title":"TneTabItem","key":"neTabItem.TneTabItem","href":"neTabItem.TneTabItem.htm","children":[{"title":"Constructors","key":"neTabItem.TneTabItem_Constructors","href":"neTabItem.TneTabItem_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabItem.TneTabItem.Create(TComponent)","href":"neTabItem.TneTabItem.Create.htm"}
,{"title":"Destroy","key":"neTabItem.TneTabItem.Destroy","href":"neTabItem.TneTabItem.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabItem.TneTabItem_Properties","href":"neTabItem.TneTabItem_Properties.htm","children":[{"title":"CanClose","key":"neTabItem.TneTabItem.CanClose","href":"neTabItem.TneTabItem.CanClose.htm"}
,{"title":"Caption","key":"neTabItem.TneTabItem.Caption","href":"neTabItem.TneTabItem.Caption.htm"}
,{"title":"CaptionAlignment","key":"neTabItem.TneTabItem.CaptionAlignment","href":"neTabItem.TneTabItem.CaptionAlignment.htm"}
,{"title":"CloseAlignment","key":"neTabItem.TneTabItem.CloseAlignment","href":"neTabItem.TneTabItem.CloseAlignment.htm"}
,{"title":"CloseImageHover","key":"neTabItem.TneTabItem.CloseImageHover","href":"neTabItem.TneTabItem.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabItem.TneTabItem.CloseImageNormal","href":"neTabItem.TneTabItem.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabItem.TneTabItem.CloseImagePressed","href":"neTabItem.TneTabItem.CloseImagePressed.htm"}
,{"title":"ControlAlignment","key":"neTabItem.TneTabItem.ControlAlignment","href":"neTabItem.TneTabItem.ControlAlignment.htm"}
,{"title":"ControlToShow","key":"neTabItem.TneTabItem.ControlToShow","href":"neTabItem.TneTabItem.ControlToShow.htm"}
,{"title":"HintInterval","key":"neTabItem.TneTabItem.HintInterval","href":"neTabItem.TneTabItem.HintInterval.htm"}
,{"title":"HintText","key":"neTabItem.TneTabItem.HintText","href":"neTabItem.TneTabItem.HintText.htm"}
,{"title":"MaxTabWidth","key":"neTabItem.TneTabItem.MaxTabWidth","href":"neTabItem.TneTabItem.MaxTabWidth.htm"}
,{"title":"MinTabWidth","key":"neTabItem.TneTabItem.MinTabWidth","href":"neTabItem.TneTabItem.MinTabWidth.htm"}
,{"title":"PopupMenuAfterDefault","key":"neTabItem.TneTabItem.PopupMenuAfterDefault","href":"neTabItem.TneTabItem.PopupMenuAfterDefault.htm"}
,{"title":"PopupMenuBeforeDefault","key":"neTabItem.TneTabItem.PopupMenuBeforeDefault","href":"neTabItem.TneTabItem.PopupMenuBeforeDefault.htm"}
,{"title":"Provider","key":"neTabItem.TneTabItem.Provider","href":"neTabItem.TneTabItem.Provider.htm"}
,{"title":"ShowControl","key":"neTabItem.TneTabItem.ShowControl","href":"neTabItem.TneTabItem.ShowControl.htm"}
,{"title":"ShowPopupMenu","key":"neTabItem.TneTabItem.ShowPopupMenu","href":"neTabItem.TneTabItem.ShowPopupMenu.htm"}
,{"title":"TabTag","key":"neTabItem.TneTabItem.TabTag","href":"neTabItem.TneTabItem.TabTag.htm"}
,{"title":"TabWidth","key":"neTabItem.TneTabItem.TabWidth","href":"neTabItem.TneTabItem.TabWidth.htm"}
]}
,{"title":"Methods","key":"neTabItem.TneTabItem_Methods","href":"neTabItem.TneTabItem_Methods.htm","children":[{"title":"ApplyStyle","key":"neTabItem.TneTabItem.ApplyStyle","href":"neTabItem.TneTabItem.ApplyStyle.htm"}
,{"title":"DoMouseLeave","key":"neTabItem.TneTabItem.DoMouseLeave","href":"neTabItem.TneTabItem.DoMouseLeave.htm"}
,{"title":"MouseClick(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseClick.htm"}
,{"title":"MouseMove(TShiftState,Single,Single)","key":"neTabItem.TneTabItem.MouseMove(TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseMove.htm"}
,{"title":"RefreshControl","key":"neTabItem.TneTabItem.RefreshControl","href":"neTabItem.TneTabItem.RefreshControl.htm"}
,{"title":"SetWidth(Single)","key":"neTabItem.TneTabItem.SetWidth(Single)","href":"neTabItem.TneTabItem.SetWidth.htm"}
,{"title":"UpdateFromProvider(INotification)","key":"neTabItem.TneTabItem.UpdateFromProvider(INotification)","href":"neTabItem.TneTabItem.UpdateFromProvider.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabItem_Enumerations","href":"neTabItem_Enumerations.htm","children":[{"title":"TCloseImagesType","key":"neTabItem.TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TMouseState","key":"neTabItem.TMouseState","href":"neTabItem.TMouseState.htm"}
]}
,{"title":"Constants","key":"neTabItem_Constants","href":"neTabItem_Constants.htm","children":[{"title":"BugVersion","key":"neTabItem.BugVersion","href":"neTabItem.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabItem.MajorVersion","href":"neTabItem.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabItem.MinorVersion","href":"neTabItem.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabItem_Routines","href":"neTabItem_Routines.htm","children":[{"title":"register","key":"neTabItem.register","href":"neTabItem.register.htm"}
]}
]}
,{"title":"neTabTypes","key":"neTabTypes","href":"neTabTypes.htm","children":[{"title":"Classes","key":"neTabTypes_Classes","href":"neTabTypes_Classes.htm","children":[{"title":"THistoryClass","key":"neTabTypes.THistoryClass","href":"neTabTypes.THistoryClass.htm","children":[{"title":"Constructors","key":"neTabTypes.THistoryClass_Constructors","href":"neTabTypes.THistoryClass_Constructors.htm","children":[{"title":"Create","key":"neTabTypes.THistoryClass.Create","href":"neTabTypes.THistoryClass.Create.htm"}
,{"title":"Destroy","key":"neTabTypes.THistoryClass.Destroy","href":"neTabTypes.THistoryClass.Destroy.htm"}
]}
,{"title":"Methods","key":"neTabTypes.THistoryClass_Methods","href":"neTabTypes.THistoryClass_Methods.htm","children":[{"title":"AddHistory(string)","key":"neTabTypes.THistoryClass.AddHistory(string)","href":"neTabTypes.THistoryClass.AddHistory.htm"}
,{"title":"DeleteHistory(string)","key":"neTabTypes.THistoryClass.DeleteHistory(string)","href":"neTabTypes.THistoryClass.DeleteHistory.htm"}
,{"title":"GetLastEntry","key":"neTabTypes.THistoryClass.GetLastEntry","href":"neTabTypes.THistoryClass.GetLastEntry.htm"}
]}
]}
,{"title":"TneHintTimer","key":"neTabTypes.TneHintTimer","href":"neTabTypes.TneHintTimer.htm","children":[{"title":"Fields","key":"neTabTypes.TneHintTimer_Fields","href":"neTabTypes.TneHintTimer_Fields.htm","children":[{"title":"MousePoint","key":"neTabTypes.TneHintTimer.MousePoint","href":"neTabTypes.TneHintTimer.MousePoint.htm"}
]}
]}
,{"title":"TneNotificationClass","key":"neTabTypes.TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm","children":[{"title":"Properties","key":"neTabTypes.TneNotificationClass_Properties","href":"neTabTypes.TneNotificationClass_Properties.htm","children":[{"title":"Action","key":"neTabTypes.TneNotificationClass.Action","href":"neTabTypes.TneNotificationClass.Action.htm"}
,{"title":"Point","key":"neTabTypes.TneNotificationClass.Point","href":"neTabTypes.TneNotificationClass.Point.htm"}
,{"title":"PopupAfter","key":"neTabTypes.TneNotificationClass.PopupAfter","href":"neTabTypes.TneNotificationClass.PopupAfter.htm"}
,{"title":"PopupBefore","key":"neTabTypes.TneNotificationClass.PopupBefore","href":"neTabTypes.TneNotificationClass.PopupBefore.htm"}
,{"title":"PopupDefault","key":"neTabTypes.TneNotificationClass.PopupDefault","href":"neTabTypes.TneNotificationClass.PopupDefault.htm"}
,{"title":"Sender","key":"neTabTypes.TneNotificationClass.Sender","href":"neTabTypes.TneNotificationClass.Sender.htm"}
,{"title":"Value","key":"neTabTypes.TneNotificationClass.Value","href":"neTabTypes.TneNotificationClass.Value.htm"}
,{"title":"ValueInt","key":"neTabTypes.TneNotificationClass.ValueInt","href":"neTabTypes.TneNotificationClass.ValueInt.htm"}
]}
]}
,{"title":"TneTimer","key":"neTabTypes.TneTimer","href":"neTabTypes.TneTimer.htm","children":[{"title":"Fields","key":"neTabTypes.TneTimer_Fields","href":"neTabTypes.TneTimer_Fields.htm","children":[{"title":"Action","key":"neTabTypes.TneTimer.Action","href":"neTabTypes.TneTimer.Action.htm"}
,{"title":"Value","key":"neTabTypes.TneTimer.Value","href":"neTabTypes.TneTimer.Value.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabTypes_Enumerations","href":"neTabTypes_Enumerations.htm","children":[{"title":"TExportElement","key":"neTabTypes.TExportElement","href":"neTabTypes.TExportElement.htm"}
]}
,{"title":"Types","key":"neTabTypes_Types","href":"neTabTypes_Types.htm","children":[{"title":"TExportElements","key":"neTabTypes.TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"TSetOfStrings","key":"neTabTypes.TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
]}
,{"title":"Constants","key":"neTabTypes_Constants","href":"neTabTypes_Constants.htm","children":[{"title":"BugVersion","key":"neTabTypes.BugVersion","href":"neTabTypes.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabTypes.MajorVersion","href":"neTabTypes.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabTypes.MinorVersion","href":"neTabTypes.MinorVersion.htm"}
,{"title":"SCloseAllTabs","key":"neTabTypes.SCloseAllTabs","href":"neTabTypes.SCloseAllTabs.htm"}
,{"title":"SCloseOtherTabs","key":"neTabTypes.SCloseOtherTabs","href":"neTabTypes.SCloseOtherTabs.htm"}
,{"title":"SCloseTab","key":"neTabTypes.SCloseTab","href":"neTabTypes.SCloseTab.htm"}
]}
]}
]}
]