[{"title":"neTabControlPackage","key":"neTabControlPackage","href":"neTabControlPackage.htm","activate":true,"children":[{"title":"neTabControl","key":"neTabControl","href":"neTabControl.htm","children":[{"title":"Classes","key":"neTabControl_Classes","href":"neTabControl_Classes.htm","children":[{"title":"THintPanel","key":"neTabControl.THintPanel","href":"neTabControl.THintPanel.htm","children":[{"title":"Properties","key":"neTabControl.THintPanel_Properties","href":"neTabControl.THintPanel_Properties.htm","children":[{"title":"HintStyle","key":"neTabControl.THintPanel.HintStyle","href":"neTabControl.THintPanel.HintStyle.htm"}
,{"title":"HintText","key":"neTabControl.THintPanel.HintText","href":"neTabControl.THintPanel.HintText.htm"}
]}
,{"title":"Methods","key":"neTabControl.THintPanel_Methods","href":"neTabControl.THintPanel_Methods.htm","children":[{"title":"ApplyStyle","key":"neTabControl.THintPanel.ApplyStyle","href":"neTabControl.THintPanel.ApplyStyle.htm"}
,{"title":"SetHintStyle(THintStyle)","key":"neTabControl.THintPanel.SetHintStyle(THintStyle)","href":"neTabControl.THintPanel.SetHintStyle.htm"}
,{"title":"SetHintText(string)","key":"neTabControl.THintPanel.SetHintText(string)","href":"neTabControl.THintPanel.SetHintText.htm"}
]}
,{"title":"Fields","key":"neTabControl.THintPanel_Fields","href":"neTabControl.THintPanel_Fields.htm","children":[{"title":"fHintStyle","key":"neTabControl.THintPanel.fHintStyle","href":"neTabControl.THintPanel.fHintStyle.htm"}
,{"title":"fHintText","key":"neTabControl.THintPanel.fHintText","href":"neTabControl.THintPanel.fHintText.htm"}
]}
]}
,{"title":"TneTabControl","key":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabControl_Constructors","href":"neTabControl.TneTabControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"Destroy","key":"neTabControl.TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabControl_Properties","href":"neTabControl.TneTabControl_Properties.htm","children":[{"title":"ActiveTag","key":"neTabControl.TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"CloseAllOtherTabsLabel","key":"neTabControl.TneTabControl.CloseAllOtherTabsLabel","href":"neTabControl.TneTabControl.CloseAllOtherTabsLabel.htm"}
,{"title":"CloseImageHover","key":"neTabControl.TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"CloseTabLabel","key":"neTabControl.TneTabControl.CloseTabLabel","href":"neTabControl.TneTabControl.CloseTabLabel.htm"}
,{"title":"CloseTabOnDoubleClick","key":"neTabControl.TneTabControl.CloseTabOnDoubleClick","href":"neTabControl.TneTabControl.CloseTabOnDoubleClick.htm"}
,{"title":"DisablePopupMenu","key":"neTabControl.TneTabControl.DisablePopupMenu","href":"neTabControl.TneTabControl.DisablePopupMenu.htm"}
,{"title":"HintShowDelay","key":"neTabControl.TneTabControl.HintShowDelay","href":"neTabControl.TneTabControl.HintShowDelay.htm"}
,{"title":"HintStyle","key":"neTabControl.TneTabControl.HintStyle","href":"neTabControl.TneTabControl.HintStyle.htm"}
,{"title":"MaxTabWidth","key":"neTabControl.TneTabControl.MaxTabWidth","href":"neTabControl.TneTabControl.MaxTabWidth.htm"}
,{"title":"MinTabWidth","key":"neTabControl.TneTabControl.MinTabWidth","href":"neTabControl.TneTabControl.MinTabWidth.htm"}
,{"title":"PopupAfterDefault","key":"neTabControl.TneTabControl.PopupAfterDefault","href":"neTabControl.TneTabControl.PopupAfterDefault.htm"}
,{"title":"PopupBeforeDefault","key":"neTabControl.TneTabControl.PopupBeforeDefault","href":"neTabControl.TneTabControl.PopupBeforeDefault.htm"}
,{"title":"Version","key":"neTabControl.TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabControl_Methods","href":"neTabControl.TneTabControl_Methods.htm","children":[{"title":"AddTab(string,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string%2CTFrame).htm"}
,{"title":"AddTab(string,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string%2CTneTabItem%2CTFrame).htm"}
,{"title":"AddTab(string,TTabItem,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TTabItem@,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string%2CTTabItem%2CTFrame).htm"}
,{"title":"CleanUpTabs","key":"neTabControl.TneTabControl.CleanUpTabs","href":"neTabControl.TneTabControl.CleanUpTabs.htm"}
,{"title":"DblClick","key":"neTabControl.TneTabControl.DblClick","href":"neTabControl.TneTabControl.DblClick.htm"}
,{"title":"DeleteAllTabs(boolean)","key":"neTabControl.TneTabControl.DeleteAllTabs(boolean)","href":"neTabControl.TneTabControl.DeleteAllTabs.htm"}
,{"title":"DeleteTab(string,Boolean)","key":"neTabControl.TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"DoChange","key":"neTabControl.TneTabControl.DoChange","href":"neTabControl.TneTabControl.DoChange.htm"}
,{"title":"FindTabOrderFromTag(string)","key":"neTabControl.TneTabControl.FindTabOrderFromTag(string)","href":"neTabControl.TneTabControl.FindTabOrderFromTag.htm"}
,{"title":"FindTagFromTabOrder(integer)","key":"neTabControl.TneTabControl.FindTagFromTabOrder(integer)","href":"neTabControl.TneTabControl.FindTagFromTabOrder.htm"}
,{"title":"GetActiveTag","key":"neTabControl.TneTabControl.GetActiveTag","href":"neTabControl.TneTabControl.GetActiveTag.htm"}
,{"title":"GetFrame(string)","key":"neTabControl.TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"GetLastVisitedTag","key":"neTabControl.TneTabControl.GetLastVisitedTag","href":"neTabControl.TneTabControl.GetLastVisitedTag.htm"}
,{"title":"GetTab(string)","key":"neTabControl.TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"GetTabsTags","key":"neTabControl.TneTabControl.GetTabsTags","href":"neTabControl.TneTabControl.GetTabsTags.htm"}
,{"title":"GetTabsText","key":"neTabControl.TneTabControl.GetTabsText","href":"neTabControl.TneTabControl.GetTabsText.htm"}
,{"title":"GetVersion","key":"neTabControl.TneTabControl.GetVersion","href":"neTabControl.TneTabControl.GetVersion.htm"}
,{"title":"InsertTab(string,Integer,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,Integer,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTFrame).htm"}
,{"title":"InsertTab(string,Integer,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,Integer,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string%2CInteger%2CTneTabItem%2CTFrame).htm"}
,{"title":"MouseEnterTabItem(TObject)","key":"neTabControl.TneTabControl.MouseEnterTabItem(TObject)","href":"neTabControl.TneTabControl.MouseEnterTabItem.htm"}
,{"title":"MouseExitTabItem","key":"neTabControl.TneTabControl.MouseExitTabItem","href":"neTabControl.TneTabControl.MouseExitTabItem.htm"}
,{"title":"MouseMoveOverTabItem(string,Single,Single)","key":"neTabControl.TneTabControl.MouseMoveOverTabItem(string,Single,Single)","href":"neTabControl.TneTabControl.MouseMoveOverTabItem.htm"}
,{"title":"OnHintTimer(TObject)","key":"neTabControl.TneTabControl.OnHintTimer(TObject)","href":"neTabControl.TneTabControl.OnHintTimer.htm"}
,{"title":"OnPopUpChangeTab(TObject)","key":"neTabControl.TneTabControl.OnPopUpChangeTab(TObject)","href":"neTabControl.TneTabControl.OnPopUpChangeTab.htm"}
,{"title":"OnPopUpMenuClose(TObject)","key":"neTabControl.TneTabControl.OnPopUpMenuClose(TObject)","href":"neTabControl.TneTabControl.OnPopUpMenuClose.htm"}
,{"title":"OnPopUpMenuCloseAllOtherTabs(TObject)","key":"neTabControl.TneTabControl.OnPopUpMenuCloseAllOtherTabs(TObject)","href":"neTabControl.TneTabControl.OnPopUpMenuCloseAllOtherTabs.htm"}
,{"title":"SaveTabs(TExportElementsSet,TSetOfString,TStringList)","key":"neTabControl.TneTabControl.SaveTabs(TExportElementsSet,TSetOfString,TStringList@)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"SetActiveTab(string)","key":"neTabControl.TneTabControl.SetActiveTab(string)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
,{"title":"SetHintShowDelay(integer)","key":"neTabControl.TneTabControl.SetHintShowDelay(integer)","href":"neTabControl.TneTabControl.SetHintShowDelay.htm"}
,{"title":"SetHintSTyle(THintStyle)","key":"neTabControl.TneTabControl.SetHintSTyle(THintStyle)","href":"neTabControl.TneTabControl.SetHintSTyle.htm"}
,{"title":"SetMaxTabWidth(Single)","key":"neTabControl.TneTabControl.SetMaxTabWidth(Single)","href":"neTabControl.TneTabControl.SetMaxTabWidth.htm"}
,{"title":"SetMinTabWidth(Single)","key":"neTabControl.TneTabControl.SetMinTabWidth(Single)","href":"neTabControl.TneTabControl.SetMinTabWidth.htm"}
,{"title":"ShowPopUpMenu(TneTabItem,Single,Single)","key":"neTabControl.TneTabControl.ShowPopUpMenu(TneTabItem,Single,Single)","href":"neTabControl.TneTabControl.ShowPopUpMenu.htm"}
]}
,{"title":"Events","key":"neTabControl.TneTabControl_Events","href":"neTabControl.TneTabControl_Events.htm","children":[{"title":"OnAfterDelete","key":"neTabControl.TneTabControl.OnAfterDelete","href":"neTabControl.TneTabControl.OnAfterDelete.htm"}
,{"title":"OnBeforeDelete","key":"neTabControl.TneTabControl.OnBeforeDelete","href":"neTabControl.TneTabControl.OnBeforeDelete.htm"}
]}
,{"title":"Fields","key":"neTabControl.TneTabControl_Fields","href":"neTabControl.TneTabControl_Fields.htm","children":[{"title":"fCloseAllOtherTabsLabel","key":"neTabControl.TneTabControl.fCloseAllOtherTabsLabel","href":"neTabControl.TneTabControl.fCloseAllOtherTabsLabel.htm"}
,{"title":"fCloseImageHover","key":"neTabControl.TneTabControl.fCloseImageHover","href":"neTabControl.TneTabControl.fCloseImageHover.htm"}
,{"title":"fCloseImageNormal","key":"neTabControl.TneTabControl.fCloseImageNormal","href":"neTabControl.TneTabControl.fCloseImageNormal.htm"}
,{"title":"fCloseImagePressed","key":"neTabControl.TneTabControl.fCloseImagePressed","href":"neTabControl.TneTabControl.fCloseImagePressed.htm"}
,{"title":"fCloseTabLabel","key":"neTabControl.TneTabControl.fCloseTabLabel","href":"neTabControl.TneTabControl.fCloseTabLabel.htm"}
,{"title":"fCloseTabOnDoubleClick","key":"neTabControl.TneTabControl.fCloseTabOnDoubleClick","href":"neTabControl.TneTabControl.fCloseTabOnDoubleClick.htm"}
,{"title":"fCurrentNETabItem","key":"neTabControl.TneTabControl.fCurrentNETabItem","href":"neTabControl.TneTabControl.fCurrentNETabItem.htm"}
,{"title":"fDictionaryFrames","key":"neTabControl.TneTabControl.fDictionaryFrames","href":"neTabControl.TneTabControl.fDictionaryFrames.htm"}
,{"title":"fDictionaryTabs","key":"neTabControl.TneTabControl.fDictionaryTabs","href":"neTabControl.TneTabControl.fDictionaryTabs.htm"}
,{"title":"fDisablePopupMenu","key":"neTabControl.TneTabControl.fDisablePopupMenu","href":"neTabControl.TneTabControl.fDisablePopupMenu.htm"}
,{"title":"fHintPanel","key":"neTabControl.TneTabControl.fHintPanel","href":"neTabControl.TneTabControl.fHintPanel.htm"}
,{"title":"fHintPopup","key":"neTabControl.TneTabControl.fHintPopup","href":"neTabControl.TneTabControl.fHintPopup.htm"}
,{"title":"fHintShowDelay","key":"neTabControl.TneTabControl.fHintShowDelay","href":"neTabControl.TneTabControl.fHintShowDelay.htm"}
,{"title":"fHintStyle","key":"neTabControl.TneTabControl.fHintStyle","href":"neTabControl.TneTabControl.fHintStyle.htm"}
,{"title":"fHintTimer","key":"neTabControl.TneTabControl.fHintTimer","href":"neTabControl.TneTabControl.fHintTimer.htm"}
,{"title":"fHistoryTags","key":"neTabControl.TneTabControl.fHistoryTags","href":"neTabControl.TneTabControl.fHistoryTags.htm"}
,{"title":"fMaxTabWidth","key":"neTabControl.TneTabControl.fMaxTabWidth","href":"neTabControl.TneTabControl.fMaxTabWidth.htm"}
,{"title":"fMinTabWidth","key":"neTabControl.TneTabControl.fMinTabWidth","href":"neTabControl.TneTabControl.fMinTabWidth.htm"}
,{"title":"fOnAfterDelete","key":"neTabControl.TneTabControl.fOnAfterDelete","href":"neTabControl.TneTabControl.fOnAfterDelete.htm"}
,{"title":"fOnBeforeDelete","key":"neTabControl.TneTabControl.fOnBeforeDelete","href":"neTabControl.TneTabControl.fOnBeforeDelete.htm"}
,{"title":"fPopupAfterDefaultMenu","key":"neTabControl.TneTabControl.fPopupAfterDefaultMenu","href":"neTabControl.TneTabControl.fPopupAfterDefaultMenu.htm"}
,{"title":"fPopupBeforeDefaultMenu","key":"neTabControl.TneTabControl.fPopupBeforeDefaultMenu","href":"neTabControl.TneTabControl.fPopupBeforeDefaultMenu.htm"}
,{"title":"fVersion","key":"neTabControl.TneTabControl.fVersion","href":"neTabControl.TneTabControl.fVersion.htm"}
]}
]}
,{"title":"TneTabItem","key":"neTabControl.TneTabItem","href":"neTabControl.TneTabItem.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabItem_Constructors","href":"neTabControl.TneTabItem_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabItem.Create(TComponent)","href":"neTabControl.TneTabItem.Create.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabItem_Properties","href":"neTabControl.TneTabItem_Properties.htm","children":[{"title":"CanClose","key":"neTabControl.TneTabItem.CanClose","href":"neTabControl.TneTabItem.CanClose.htm"}
,{"title":"CloseImageHover","key":"neTabControl.TneTabItem.CloseImageHover","href":"neTabControl.TneTabItem.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabItem.CloseImageNormal","href":"neTabControl.TneTabItem.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabItem.CloseImagePressed","href":"neTabControl.TneTabItem.CloseImagePressed.htm"}
,{"title":"Deleted","key":"neTabControl.TneTabItem.Deleted","href":"neTabControl.TneTabItem.Deleted.htm"}
,{"title":"Icon","key":"neTabControl.TneTabItem.Icon","href":"neTabControl.TneTabItem.Icon.htm"}
,{"title":"Identifier","key":"neTabControl.TneTabItem.Identifier","href":"neTabControl.TneTabItem.Identifier.htm"}
,{"title":"ShowIcon","key":"neTabControl.TneTabItem.ShowIcon","href":"neTabControl.TneTabItem.ShowIcon.htm"}
,{"title":"TabControlParent","key":"neTabControl.TneTabItem.TabControlParent","href":"neTabControl.TneTabItem.TabControlParent.htm"}
,{"title":"TagVariant","key":"neTabControl.TneTabItem.TagVariant","href":"neTabControl.TneTabItem.TagVariant.htm"}
,{"title":"Version","key":"neTabControl.TneTabItem.Version","href":"neTabControl.TneTabItem.Version.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabItem_Methods","href":"neTabControl.TneTabItem_Methods.htm","children":[{"title":"AdjustTabWidth(single,Single)","key":"neTabControl.TneTabItem.AdjustTabWidth(single,Single)","href":"neTabControl.TneTabItem.AdjustTabWidth.htm"}
,{"title":"ApplyStyle","key":"neTabControl.TneTabItem.ApplyStyle","href":"neTabControl.TneTabItem.ApplyStyle.htm"}
,{"title":"DblClick","key":"neTabControl.TneTabItem.DblClick","href":"neTabControl.TneTabItem.DblClick.htm"}
,{"title":"GetVersion","key":"neTabControl.TneTabItem.GetVersion","href":"neTabControl.TneTabItem.GetVersion.htm"}
,{"title":"MouseClick(TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseClick.htm"}
,{"title":"MouseDown(TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.MouseDown(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseDown.htm"}
,{"title":"MouseUp(TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.MouseUp(TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.MouseUp.htm"}
,{"title":"NewOnMouseEnter(TObject)","key":"neTabControl.TneTabItem.NewOnMouseEnter(TObject)","href":"neTabControl.TneTabItem.NewOnMouseEnter.htm"}
,{"title":"NewOnMouseLeave(TObject)","key":"neTabControl.TneTabItem.NewOnMouseLeave(TObject)","href":"neTabControl.TneTabItem.NewOnMouseLeave.htm"}
,{"title":"NewOnMouseMove(TObject,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.NewOnMouseMove(TObject,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.NewOnMouseMove.htm"}
,{"title":"OnCloseImageClick(TObject)","key":"neTabControl.TneTabItem.OnCloseImageClick(TObject)","href":"neTabControl.TneTabItem.OnCloseImageClick.htm"}
,{"title":"OnCloseImageHoverClick(TObject)","key":"neTabControl.TneTabItem.OnCloseImageHoverClick(TObject)","href":"neTabControl.TneTabItem.OnCloseImageHoverClick.htm"}
,{"title":"OnCloseImageLeave(TObject)","key":"neTabControl.TneTabItem.OnCloseImageLeave(TObject)","href":"neTabControl.TneTabItem.OnCloseImageLeave.htm"}
,{"title":"OnCloseImageMouseDown(TObject,TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.OnCloseImageMouseDown(TObject,TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.OnCloseImageMouseDown.htm"}
,{"title":"OnCloseImageMouseUp(TObject,TMouseButton,TShiftState,Single,Single)","key":"neTabControl.TneTabItem.OnCloseImageMouseUp(TObject,TMouseButton,TShiftState,Single,Single)","href":"neTabControl.TneTabItem.OnCloseImageMouseUp.htm"}
,{"title":"SetCanClose(Boolean)","key":"neTabControl.TneTabItem.SetCanClose(Boolean)","href":"neTabControl.TneTabItem.SetCanClose.htm"}
,{"title":"SetCloseImageHover(TBitmap)","key":"neTabControl.TneTabItem.SetCloseImageHover(TBitmap)","href":"neTabControl.TneTabItem.SetCloseImageHover.htm"}
,{"title":"SetCloseImageNormal(TBitmap)","key":"neTabControl.TneTabItem.SetCloseImageNormal(TBitmap)","href":"neTabControl.TneTabItem.SetCloseImageNormal.htm"}
,{"title":"SetCloseImagePressed(TBitMap)","key":"neTabControl.TneTabItem.SetCloseImagePressed(TBitMap)","href":"neTabControl.TneTabItem.SetCloseImagePressed.htm"}
,{"title":"SetIcon(TBitmap)","key":"neTabControl.TneTabItem.SetIcon(TBitmap)","href":"neTabControl.TneTabItem.SetIcon.htm"}
,{"title":"SetShowIcon(Boolean)","key":"neTabControl.TneTabItem.SetShowIcon(Boolean)","href":"neTabControl.TneTabItem.SetShowIcon.htm"}
]}
,{"title":"Fields","key":"neTabControl.TneTabItem_Fields","href":"neTabControl.TneTabItem_Fields.htm","children":[{"title":"fCanClose","key":"neTabControl.TneTabItem.fCanClose","href":"neTabControl.TneTabItem.fCanClose.htm"}
,{"title":"fCloseImageHover","key":"neTabControl.TneTabItem.fCloseImageHover","href":"neTabControl.TneTabItem.fCloseImageHover.htm"}
,{"title":"fCloseImageNormal","key":"neTabControl.TneTabItem.fCloseImageNormal","href":"neTabControl.TneTabItem.fCloseImageNormal.htm"}
,{"title":"fCloseImagePressed","key":"neTabControl.TneTabItem.fCloseImagePressed","href":"neTabControl.TneTabItem.fCloseImagePressed.htm"}
,{"title":"fDeleted","key":"neTabControl.TneTabItem.fDeleted","href":"neTabControl.TneTabItem.fDeleted.htm"}
,{"title":"fIcon","key":"neTabControl.TneTabItem.fIcon","href":"neTabControl.TneTabItem.fIcon.htm"}
,{"title":"fIdentifier","key":"neTabControl.TneTabItem.fIdentifier","href":"neTabControl.TneTabItem.fIdentifier.htm"}
,{"title":"fIsMousePressed","key":"neTabControl.TneTabItem.fIsMousePressed","href":"neTabControl.TneTabItem.fIsMousePressed.htm"}
,{"title":"fShowIcon","key":"neTabControl.TneTabItem.fShowIcon","href":"neTabControl.TneTabItem.fShowIcon.htm"}
,{"title":"fTabControlParent","key":"neTabControl.TneTabItem.fTabControlParent","href":"neTabControl.TneTabItem.fTabControlParent.htm"}
,{"title":"fTagVariant","key":"neTabControl.TneTabItem.fTagVariant","href":"neTabControl.TneTabItem.fTagVariant.htm"}
,{"title":"fVersion","key":"neTabControl.TneTabItem.fVersion","href":"neTabControl.TneTabItem.fVersion.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabControl_Enumerations","href":"neTabControl_Enumerations.htm","children":[{"title":"TExportElements","key":"neTabControl.TExportElements","href":"neTabControl.TExportElements.htm"}
,{"title":"THintStyle","key":"neTabControl.THintStyle","href":"neTabControl.THintStyle.htm"}
]}
,{"title":"Delegates","key":"neTabControl_Delegates","href":"neTabControl_Delegates.htm","children":[{"title":"TOnAfterDelete","key":"neTabControl.TOnAfterDelete","href":"neTabControl.TOnAfterDelete.htm"}
,{"title":"TOnBeforeDelete","key":"neTabControl.TOnBeforeDelete","href":"neTabControl.TOnBeforeDelete.htm"}
]}
,{"title":"Types","key":"neTabControl_Types","href":"neTabControl_Types.htm","children":[{"title":"TExportElementsSet","key":"neTabControl.TExportElementsSet","href":"neTabControl.TExportElementsSet.htm"}
,{"title":"TSetOfString","key":"neTabControl.TSetOfString","href":"neTabControl.TSetOfString.htm"}
]}
,{"title":"Constants","key":"neTabControl_Constants","href":"neTabControl_Constants.htm","children":[{"title":"BugVersion","key":"neTabControl.BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabControl.MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabControl.MinorVersion","href":"neTabControl.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabControl_Routines","href":"neTabControl_Routines.htm","children":[{"title":"FindParentForm(TFmxObject)","key":"neTabControl.FindParentForm(TFmxObject)","href":"neTabControl.FindParentForm.htm"}
,{"title":"FindParentNeTabItem(TFMXObject)","key":"neTabControl.FindParentNeTabItem(TFMXObject)","href":"neTabControl.FindParentNeTabItem.htm"}
,{"title":"Register","key":"neTabControl.Register","href":"neTabControl.Register.htm"}
,{"title":"ResizeBitmap(TBitmap,Integer,Integer)","key":"neTabControl.ResizeBitmap(TBitmap,Integer,Integer)","href":"neTabControl.ResizeBitmap.htm"}
]}
]}
]}
]