[{"title":"neTabControlPackage","key":"neTabControlPackage","href":"neTabControlPackage.htm","activate":true,"children":[{"title":"neTabControl","key":"neTabControl","href":"neTabControl.htm","children":[{"title":"Classes","key":"neTabControl_Classes","href":"neTabControl_Classes.htm","children":[{"title":"TneTabControl","key":"neTabControl.TneTabControl","href":"neTabControl.TneTabControl.htm","children":[{"title":"Constructors","key":"neTabControl.TneTabControl_Constructors","href":"neTabControl.TneTabControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabControl.TneTabControl.Create(TComponent)","href":"neTabControl.TneTabControl.Create.htm"}
,{"title":"Destroy","key":"neTabControl.TneTabControl.Destroy","href":"neTabControl.TneTabControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabControl.TneTabControl_Properties","href":"neTabControl.TneTabControl_Properties.htm","children":[{"title":"ActiveTab","key":"neTabControl.TneTabControl.ActiveTab","href":"neTabControl.TneTabControl.ActiveTab.htm"}
,{"title":"ActiveTag","key":"neTabControl.TneTabControl.ActiveTag","href":"neTabControl.TneTabControl.ActiveTag.htm"}
,{"title":"Align","key":"neTabControl.TneTabControl.Align","href":"neTabControl.TneTabControl.Align.htm"}
,{"title":"Anchors","key":"neTabControl.TneTabControl.Anchors","href":"neTabControl.TneTabControl.Anchors.htm"}
,{"title":"CanParentFocus","key":"neTabControl.TneTabControl.CanParentFocus","href":"neTabControl.TneTabControl.CanParentFocus.htm"}
,{"title":"ClipChildren","key":"neTabControl.TneTabControl.ClipChildren","href":"neTabControl.TneTabControl.ClipChildren.htm"}
,{"title":"ClipParent","key":"neTabControl.TneTabControl.ClipParent","href":"neTabControl.TneTabControl.ClipParent.htm"}
,{"title":"CloseAllOtherTabsText","key":"neTabControl.TneTabControl.CloseAllOtherTabsText","href":"neTabControl.TneTabControl.CloseAllOtherTabsText.htm"}
,{"title":"CloseAllTabsText","key":"neTabControl.TneTabControl.CloseAllTabsText","href":"neTabControl.TneTabControl.CloseAllTabsText.htm"}
,{"title":"CloseImageHover","key":"neTabControl.TneTabControl.CloseImageHover","href":"neTabControl.TneTabControl.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabControl.TneTabControl.CloseImageNormal","href":"neTabControl.TneTabControl.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabControl.TneTabControl.CloseImagePressed","href":"neTabControl.TneTabControl.CloseImagePressed.htm"}
,{"title":"CloseTabText","key":"neTabControl.TneTabControl.CloseTabText","href":"neTabControl.TneTabControl.CloseTabText.htm"}
,{"title":"Cursor","key":"neTabControl.TneTabControl.Cursor","href":"neTabControl.TneTabControl.Cursor.htm"}
,{"title":"DisableFocusEffect","key":"neTabControl.TneTabControl.DisableFocusEffect","href":"neTabControl.TneTabControl.DisableFocusEffect.htm"}
,{"title":"DragMode","key":"neTabControl.TneTabControl.DragMode","href":"neTabControl.TneTabControl.DragMode.htm"}
,{"title":"Enabled","key":"neTabControl.TneTabControl.Enabled","href":"neTabControl.TneTabControl.Enabled.htm"}
,{"title":"EnableDragHighlight","key":"neTabControl.TneTabControl.EnableDragHighlight","href":"neTabControl.TneTabControl.EnableDragHighlight.htm"}
,{"title":"Height","key":"neTabControl.TneTabControl.Height","href":"neTabControl.TneTabControl.Height.htm"}
,{"title":"HintInterval","key":"neTabControl.TneTabControl.HintInterval","href":"neTabControl.TneTabControl.HintInterval.htm"}
,{"title":"HintType","key":"neTabControl.TneTabControl.HintType","href":"neTabControl.TneTabControl.HintType.htm"}
,{"title":"HitTest","key":"neTabControl.TneTabControl.HitTest","href":"neTabControl.TneTabControl.HitTest.htm"}
,{"title":"Locked","key":"neTabControl.TneTabControl.Locked","href":"neTabControl.TneTabControl.Locked.htm"}
,{"title":"Margins","key":"neTabControl.TneTabControl.Margins","href":"neTabControl.TneTabControl.Margins.htm"}
,{"title":"OnApplyStyleLookup","key":"neTabControl.TneTabControl.OnApplyStyleLookup","href":"neTabControl.TneTabControl.OnApplyStyleLookup.htm"}
,{"title":"OnCanFocus","key":"neTabControl.TneTabControl.OnCanFocus","href":"neTabControl.TneTabControl.OnCanFocus.htm"}
,{"title":"OnChange","key":"neTabControl.TneTabControl.OnChange","href":"neTabControl.TneTabControl.OnChange.htm"}
,{"title":"OnClick","key":"neTabControl.TneTabControl.OnClick","href":"neTabControl.TneTabControl.OnClick.htm"}
,{"title":"OnDblClick","key":"neTabControl.TneTabControl.OnDblClick","href":"neTabControl.TneTabControl.OnDblClick.htm"}
,{"title":"OnDragDrop","key":"neTabControl.TneTabControl.OnDragDrop","href":"neTabControl.TneTabControl.OnDragDrop.htm"}
,{"title":"OnDragEnd","key":"neTabControl.TneTabControl.OnDragEnd","href":"neTabControl.TneTabControl.OnDragEnd.htm"}
,{"title":"OnDragEnter","key":"neTabControl.TneTabControl.OnDragEnter","href":"neTabControl.TneTabControl.OnDragEnter.htm"}
,{"title":"OnDragLeave","key":"neTabControl.TneTabControl.OnDragLeave","href":"neTabControl.TneTabControl.OnDragLeave.htm"}
,{"title":"OnDragOver","key":"neTabControl.TneTabControl.OnDragOver","href":"neTabControl.TneTabControl.OnDragOver.htm"}
,{"title":"OnEnter","key":"neTabControl.TneTabControl.OnEnter","href":"neTabControl.TneTabControl.OnEnter.htm"}
,{"title":"OnExit","key":"neTabControl.TneTabControl.OnExit","href":"neTabControl.TneTabControl.OnExit.htm"}
,{"title":"OnKeyDown","key":"neTabControl.TneTabControl.OnKeyDown","href":"neTabControl.TneTabControl.OnKeyDown.htm"}
,{"title":"OnKeyUp","key":"neTabControl.TneTabControl.OnKeyUp","href":"neTabControl.TneTabControl.OnKeyUp.htm"}
,{"title":"OnMouseDown","key":"neTabControl.TneTabControl.OnMouseDown","href":"neTabControl.TneTabControl.OnMouseDown.htm"}
,{"title":"OnMouseEnter","key":"neTabControl.TneTabControl.OnMouseEnter","href":"neTabControl.TneTabControl.OnMouseEnter.htm"}
,{"title":"OnMouseLeave","key":"neTabControl.TneTabControl.OnMouseLeave","href":"neTabControl.TneTabControl.OnMouseLeave.htm"}
,{"title":"OnMouseMove","key":"neTabControl.TneTabControl.OnMouseMove","href":"neTabControl.TneTabControl.OnMouseMove.htm"}
,{"title":"OnMouseUp","key":"neTabControl.TneTabControl.OnMouseUp","href":"neTabControl.TneTabControl.OnMouseUp.htm"}
,{"title":"OnMouseWheel","key":"neTabControl.TneTabControl.OnMouseWheel","href":"neTabControl.TneTabControl.OnMouseWheel.htm"}
,{"title":"OnPaint","key":"neTabControl.TneTabControl.OnPaint","href":"neTabControl.TneTabControl.OnPaint.htm"}
,{"title":"OnPainting","key":"neTabControl.TneTabControl.OnPainting","href":"neTabControl.TneTabControl.OnPainting.htm"}
,{"title":"OnResize","key":"neTabControl.TneTabControl.OnResize","href":"neTabControl.TneTabControl.OnResize.htm"}
,{"title":"Opacity","key":"neTabControl.TneTabControl.Opacity","href":"neTabControl.TneTabControl.Opacity.htm"}
,{"title":"Padding","key":"neTabControl.TneTabControl.Padding","href":"neTabControl.TneTabControl.Padding.htm"}
,{"title":"PopupMenu","key":"neTabControl.TneTabControl.PopupMenu","href":"neTabControl.TneTabControl.PopupMenu.htm"}
,{"title":"Position","key":"neTabControl.TneTabControl.Position","href":"neTabControl.TneTabControl.Position.htm"}
,{"title":"RotationAngle","key":"neTabControl.TneTabControl.RotationAngle","href":"neTabControl.TneTabControl.RotationAngle.htm"}
,{"title":"RotationCenter","key":"neTabControl.TneTabControl.RotationCenter","href":"neTabControl.TneTabControl.RotationCenter.htm"}
,{"title":"Scale","key":"neTabControl.TneTabControl.Scale","href":"neTabControl.TneTabControl.Scale.htm"}
,{"title":"Size","key":"neTabControl.TneTabControl.Size","href":"neTabControl.TneTabControl.Size.htm"}
,{"title":"StyleLookup","key":"neTabControl.TneTabControl.StyleLookup","href":"neTabControl.TneTabControl.StyleLookup.htm"}
,{"title":"TabAnimation","key":"neTabControl.TneTabControl.TabAnimation","href":"neTabControl.TneTabControl.TabAnimation.htm"}
,{"title":"TabAnimationDuration","key":"neTabControl.TneTabControl.TabAnimationDuration","href":"neTabControl.TneTabControl.TabAnimationDuration.htm"}
,{"title":"TabAnimationInterpolation","key":"neTabControl.TneTabControl.TabAnimationInterpolation","href":"neTabControl.TneTabControl.TabAnimationInterpolation.htm"}
,{"title":"TabAnimationType","key":"neTabControl.TneTabControl.TabAnimationType","href":"neTabControl.TneTabControl.TabAnimationType.htm"}
,{"title":"TabCount","key":"neTabControl.TneTabControl.TabCount","href":"neTabControl.TneTabControl.TabCount.htm"}
,{"title":"TabHeight","key":"neTabControl.TneTabControl.TabHeight","href":"neTabControl.TneTabControl.TabHeight.htm"}
,{"title":"TabOrder","key":"neTabControl.TneTabControl.TabOrder","href":"neTabControl.TneTabControl.TabOrder.htm"}
,{"title":"TabOrientation","key":"neTabControl.TneTabControl.TabOrientation","href":"neTabControl.TneTabControl.TabOrientation.htm"}
,{"title":"TabPosition","key":"neTabControl.TneTabControl.TabPosition","href":"neTabControl.TneTabControl.TabPosition.htm"}
,{"title":"Tabs[Integer]","key":"neTabControl.TneTabControl.Tabs(Integer)","href":"neTabControl.TneTabControl.Tabs[Integer].htm"}
,{"title":"Transition","key":"neTabControl.TneTabControl.Transition","href":"neTabControl.TneTabControl.Transition.htm"}
,{"title":"Version","key":"neTabControl.TneTabControl.Version","href":"neTabControl.TneTabControl.Version.htm"}
,{"title":"Visible","key":"neTabControl.TneTabControl.Visible","href":"neTabControl.TneTabControl.Visible.htm"}
,{"title":"Width","key":"neTabControl.TneTabControl.Width","href":"neTabControl.TneTabControl.Width.htm"}
]}
,{"title":"Methods","key":"neTabControl.TneTabControl_Methods","href":"neTabControl.TneTabControl_Methods.htm","children":[{"title":"AddSidebarControl(TControl,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.AddSidebarControl(TControl,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.AddSidebarControl.htm"}
,{"title":"AddTab(string)","key":"neTabControl.TneTabControl.AddTab(string)","href":"neTabControl.TneTabControl.AddTab(string).htm"}
,{"title":"AddTab(string,TneTabItem)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem).htm"}
,{"title":"AddTab(string,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.AddTab(string,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.AddTab(string,TneTabItem,TFrame).htm"}
,{"title":"DeleteAllTabs(Boolean)","key":"neTabControl.TneTabControl.DeleteAllTabs(Boolean)","href":"neTabControl.TneTabControl.DeleteAllTabs.htm"}
,{"title":"DeleteSidebarControl(Integer,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.DeleteSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.DeleteSidebarControl.htm"}
,{"title":"DeleteTab(string,Boolean)","key":"neTabControl.TneTabControl.DeleteTab(string,Boolean)","href":"neTabControl.TneTabControl.DeleteTab.htm"}
,{"title":"DoMainChange(TneDoChangeType)","key":"neTabControl.TneTabControl.DoMainChange(TneDoChangeType)","href":"neTabControl.TneTabControl.DoMainChange.htm"}
,{"title":"GetControl(string)","key":"neTabControl.TneTabControl.GetControl(string)","href":"neTabControl.TneTabControl.GetControl.htm"}
,{"title":"GetFrame(string)","key":"neTabControl.TneTabControl.GetFrame(string)","href":"neTabControl.TneTabControl.GetFrame.htm"}
,{"title":"GetSidebarControl(Integer,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.GetSidebarControl(Integer,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControl.htm"}
,{"title":"GetSidebarControlCount(TneSibebarControlPosition)","key":"neTabControl.TneTabControl.GetSidebarControlCount(TneSibebarControlPosition)","href":"neTabControl.TneTabControl.GetSidebarControlCount.htm"}
,{"title":"GetTab(string)","key":"neTabControl.TneTabControl.GetTab(string)","href":"neTabControl.TneTabControl.GetTab.htm"}
,{"title":"GetTabAnimation","key":"neTabControl.TneTabControl.GetTabAnimation","href":"neTabControl.TneTabControl.GetTabAnimation.htm"}
,{"title":"GetTabAnimationDuration","key":"neTabControl.TneTabControl.GetTabAnimationDuration","href":"neTabControl.TneTabControl.GetTabAnimationDuration.htm"}
,{"title":"GetTabAnimationInterpolation","key":"neTabControl.TneTabControl.GetTabAnimationInterpolation","href":"neTabControl.TneTabControl.GetTabAnimationInterpolation.htm"}
,{"title":"GetTabAnimationType","key":"neTabControl.TneTabControl.GetTabAnimationType","href":"neTabControl.TneTabControl.GetTabAnimationType.htm"}
,{"title":"GetTabByIndex(Integer)","key":"neTabControl.TneTabControl.GetTabByIndex(Integer)","href":"neTabControl.TneTabControl.GetTabByIndex.htm"}
,{"title":"GetTabCount","key":"neTabControl.TneTabControl.GetTabCount","href":"neTabControl.TneTabControl.GetTabCount.htm"}
,{"title":"GetTabItemsList(TList)","key":"neTabControl.TneTabControl.GetTabItemsList(TList@)","href":"neTabControl.TneTabControl.GetTabItemsList.htm"}
,{"title":"GetTag(Integer)","key":"neTabControl.TneTabControl.GetTag(Integer)","href":"neTabControl.TneTabControl.GetTag.htm"}
,{"title":"GetTagList(TStringList)","key":"neTabControl.TneTabControl.GetTagList(TStringList@)","href":"neTabControl.TneTabControl.GetTagList.htm"}
,{"title":"GetVersion","key":"neTabControl.TneTabControl.GetVersion","href":"neTabControl.TneTabControl.GetVersion.htm"}
,{"title":"InsertTab(string,integer)","key":"neTabControl.TneTabControl.InsertTab(string,integer)","href":"neTabControl.TneTabControl.InsertTab(string,integer).htm"}
,{"title":"InsertTab(string,integer,TneTabItem)","key":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem@)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem).htm"}
,{"title":"InsertTab(string,integer,TneTabItem,TFrame)","key":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem@,TFrame@)","href":"neTabControl.TneTabControl.InsertTab(string,integer,TneTabItem,TFrame).htm"}
,{"title":"OnChangeTab(TObject)","key":"neTabControl.TneTabControl.OnChangeTab(TObject)","href":"neTabControl.TneTabControl.OnChangeTab.htm"}
,{"title":"OnCloseAllTabs(TObject)","key":"neTabControl.TneTabControl.OnCloseAllTabs(TObject)","href":"neTabControl.TneTabControl.OnCloseAllTabs.htm"}
,{"title":"OnCloseHintTimer(TObject)","key":"neTabControl.TneTabControl.OnCloseHintTimer(TObject)","href":"neTabControl.TneTabControl.OnCloseHintTimer.htm"}
,{"title":"OnCloseOtherTabs(TObject)","key":"neTabControl.TneTabControl.OnCloseOtherTabs(TObject)","href":"neTabControl.TneTabControl.OnCloseOtherTabs.htm"}
,{"title":"OnInternalTimer(TObject)","key":"neTabControl.TneTabControl.OnInternalTimer(TObject)","href":"neTabControl.TneTabControl.OnInternalTimer.htm"}
,{"title":"OnMainBarChange(TObject)","key":"neTabControl.TneTabControl.OnMainBarChange(TObject)","href":"neTabControl.TneTabControl.OnMainBarChange.htm"}
,{"title":"OnMouseEnterToMainControl(TObject)","key":"neTabControl.TneTabControl.OnMouseEnterToMainControl(TObject)","href":"neTabControl.TneTabControl.OnMouseEnterToMainControl.htm"}
,{"title":"OnSelectTabInPopupMenu(TObject)","key":"neTabControl.TneTabControl.OnSelectTabInPopupMenu(TObject)","href":"neTabControl.TneTabControl.OnSelectTabInPopupMenu.htm"}
,{"title":"OnTabBarChange(TObject)","key":"neTabControl.TneTabControl.OnTabBarChange(TObject)","href":"neTabControl.TneTabControl.OnTabBarChange.htm"}
,{"title":"RefreshControl(string)","key":"neTabControl.TneTabControl.RefreshControl(string)","href":"neTabControl.TneTabControl.RefreshControl(string).htm"}
,{"title":"RefreshTabHeight(string)","key":"neTabControl.TneTabControl.RefreshTabHeight(string)","href":"neTabControl.TneTabControl.RefreshTabHeight(string).htm"}
,{"title":"SaveTabs(TExportElements,TSetOfStrings,TStringList)","key":"neTabControl.TneTabControl.SaveTabs(TExportElements,TSetOfStrings,TStringList@)","href":"neTabControl.TneTabControl.SaveTabs.htm"}
,{"title":"SetActiveTab(TneTabItem)","key":"neTabControl.TneTabControl.SetActiveTab(TneTabItem)","href":"neTabControl.TneTabControl.SetActiveTab.htm"}
,{"title":"SetActiveTag(string)","key":"neTabControl.TneTabControl.SetActiveTag(string)","href":"neTabControl.TneTabControl.SetActiveTag.htm"}
,{"title":"SetHintInterval(Cardinal)","key":"neTabControl.TneTabControl.SetHintInterval(Cardinal)","href":"neTabControl.TneTabControl.SetHintInterval.htm"}
,{"title":"setTabAnimation(TShowTabAnimation)","key":"neTabControl.TneTabControl.setTabAnimation(TShowTabAnimation)","href":"neTabControl.TneTabControl.setTabAnimation.htm"}
,{"title":"setTabAnimationDuration(double)","key":"neTabControl.TneTabControl.setTabAnimationDuration(double)","href":"neTabControl.TneTabControl.setTabAnimationDuration.htm"}
,{"title":"SetTabAnimationInterpolation(TInterpolationType)","key":"neTabControl.TneTabControl.SetTabAnimationInterpolation(TInterpolationType)","href":"neTabControl.TneTabControl.SetTabAnimationInterpolation.htm"}
,{"title":"setTabAnimationType(TAnimationType)","key":"neTabControl.TneTabControl.setTabAnimationType(TAnimationType)","href":"neTabControl.TneTabControl.setTabAnimationType.htm"}
,{"title":"SetTabHeight(Integer)","key":"neTabControl.TneTabControl.SetTabHeight(Integer)","href":"neTabControl.TneTabControl.SetTabHeight.htm"}
,{"title":"SetTabOrientation(TneTabOrientation)","key":"neTabControl.TneTabControl.SetTabOrientation(TneTabOrientation)","href":"neTabControl.TneTabControl.SetTabOrientation.htm"}
,{"title":"SetTabPosition(TTabPosition)","key":"neTabControl.TneTabControl.SetTabPosition(TTabPosition)","href":"neTabControl.TneTabControl.SetTabPosition.htm"}
,{"title":"ShowHint(string,TPointF)","key":"neTabControl.TneTabControl.ShowHint(string,TPointF)","href":"neTabControl.TneTabControl.ShowHint.htm"}
,{"title":"ShowPopupMenu(INotification)","key":"neTabControl.TneTabControl.ShowPopupMenu(INotification)","href":"neTabControl.TneTabControl.ShowPopupMenu.htm"}
,{"title":"ToggleVisible(Boolean,TneSibebarControlPosition)","key":"neTabControl.TneTabControl.ToggleVisible(Boolean,TneSibebarControlPosition)","href":"neTabControl.TneTabControl.ToggleVisible.htm"}
,{"title":"UpdateFromProvider(INotification)","key":"neTabControl.TneTabControl.UpdateFromProvider(INotification)","href":"neTabControl.TneTabControl.UpdateFromProvider.htm"}
,{"title":"UpdatePosition","key":"neTabControl.TneTabControl.UpdatePosition","href":"neTabControl.TneTabControl.UpdatePosition.htm"}
]}
,{"title":"Events","key":"neTabControl.TneTabControl_Events","href":"neTabControl.TneTabControl_Events.htm","children":[{"title":"OnAfterAddItem","key":"neTabControl.TneTabControl.OnAfterAddItem","href":"neTabControl.TneTabControl.OnAfterAddItem.htm"}
,{"title":"OnAfterAddSidebarControl","key":"neTabControl.TneTabControl.OnAfterAddSidebarControl","href":"neTabControl.TneTabControl.OnAfterAddSidebarControl.htm"}
,{"title":"OnAfterCloseAllItems","key":"neTabControl.TneTabControl.OnAfterCloseAllItems","href":"neTabControl.TneTabControl.OnAfterCloseAllItems.htm"}
,{"title":"OnAfterCloseOtherItems","key":"neTabControl.TneTabControl.OnAfterCloseOtherItems","href":"neTabControl.TneTabControl.OnAfterCloseOtherItems.htm"}
,{"title":"OnAfterDeleteItem","key":"neTabControl.TneTabControl.OnAfterDeleteItem","href":"neTabControl.TneTabControl.OnAfterDeleteItem.htm"}
,{"title":"OnAfterDeleteSidebarControl","key":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.OnAfterDeleteSidebarControl.htm"}
,{"title":"OnBeforeAddItem","key":"neTabControl.TneTabControl.OnBeforeAddItem","href":"neTabControl.TneTabControl.OnBeforeAddItem.htm"}
,{"title":"OnBeforeAddSidebarControl","key":"neTabControl.TneTabControl.OnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.OnBeforeAddSidebarControl.htm"}
,{"title":"OnBeforeCloseAllItems","key":"neTabControl.TneTabControl.OnBeforeCloseAllItems","href":"neTabControl.TneTabControl.OnBeforeCloseAllItems.htm"}
,{"title":"OnBeforeCloseOtherItems","key":"neTabControl.TneTabControl.OnBeforeCloseOtherItems","href":"neTabControl.TneTabControl.OnBeforeCloseOtherItems.htm"}
,{"title":"OnBeforeDeleteItem","key":"neTabControl.TneTabControl.OnBeforeDeleteItem","href":"neTabControl.TneTabControl.OnBeforeDeleteItem.htm"}
,{"title":"OnBeforeDeleteSidebarControl","key":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.OnBeforeDeleteSidebarControl.htm"}
,{"title":"OnBeforePopupMenu","key":"neTabControl.TneTabControl.OnBeforePopupMenu","href":"neTabControl.TneTabControl.OnBeforePopupMenu.htm"}
,{"title":"OnCustomHint","key":"neTabControl.TneTabControl.OnCustomHint","href":"neTabControl.TneTabControl.OnCustomHint.htm"}
]}
,{"title":"Fields","key":"neTabControl.TneTabControl_Fields","href":"neTabControl.TneTabControl_Fields.htm","children":[{"title":"fActiveTab","key":"neTabControl.TneTabControl.fActiveTab","href":"neTabControl.TneTabControl.fActiveTab.htm"}
,{"title":"fActiveTag","key":"neTabControl.TneTabControl.fActiveTag","href":"neTabControl.TneTabControl.fActiveTag.htm"}
,{"title":"fCloseAllOtherTabsText","key":"neTabControl.TneTabControl.fCloseAllOtherTabsText","href":"neTabControl.TneTabControl.fCloseAllOtherTabsText.htm"}
,{"title":"fCloseAllTabsText","key":"neTabControl.TneTabControl.fCloseAllTabsText","href":"neTabControl.TneTabControl.fCloseAllTabsText.htm"}
,{"title":"fCloseImageHover","key":"neTabControl.TneTabControl.fCloseImageHover","href":"neTabControl.TneTabControl.fCloseImageHover.htm"}
,{"title":"fCloseImageNormal","key":"neTabControl.TneTabControl.fCloseImageNormal","href":"neTabControl.TneTabControl.fCloseImageNormal.htm"}
,{"title":"fCloseImagePressed","key":"neTabControl.TneTabControl.fCloseImagePressed","href":"neTabControl.TneTabControl.fCloseImagePressed.htm"}
,{"title":"fCloseTabText","key":"neTabControl.TneTabControl.fCloseTabText","href":"neTabControl.TneTabControl.fCloseTabText.htm"}
,{"title":"fCloseTimer","key":"neTabControl.TneTabControl.fCloseTimer","href":"neTabControl.TneTabControl.fCloseTimer.htm"}
,{"title":"fFramesDictionary","key":"neTabControl.TneTabControl.fFramesDictionary","href":"neTabControl.TneTabControl.fFramesDictionary.htm"}
,{"title":"fHintInterval","key":"neTabControl.TneTabControl.fHintInterval","href":"neTabControl.TneTabControl.fHintInterval.htm"}
,{"title":"fHintType","key":"neTabControl.TneTabControl.fHintType","href":"neTabControl.TneTabControl.fHintType.htm"}
,{"title":"fHistoryList","key":"neTabControl.TneTabControl.fHistoryList","href":"neTabControl.TneTabControl.fHistoryList.htm"}
,{"title":"fInternalTimer","key":"neTabControl.TneTabControl.fInternalTimer","href":"neTabControl.TneTabControl.fInternalTimer.htm"}
,{"title":"fLeftLayout","key":"neTabControl.TneTabControl.fLeftLayout","href":"neTabControl.TneTabControl.fLeftLayout.htm"}
,{"title":"fLeftSidebarControls","key":"neTabControl.TneTabControl.fLeftSidebarControls","href":"neTabControl.TneTabControl.fLeftSidebarControls.htm"}
,{"title":"fMainControl","key":"neTabControl.TneTabControl.fMainControl","href":"neTabControl.TneTabControl.fMainControl.htm"}
,{"title":"fMainGridLayout","key":"neTabControl.TneTabControl.fMainGridLayout","href":"neTabControl.TneTabControl.fMainGridLayout.htm"}
,{"title":"fMainLayout","key":"neTabControl.TneTabControl.fMainLayout","href":"neTabControl.TneTabControl.fMainLayout.htm"}
,{"title":"fMainTabsDictionary","key":"neTabControl.TneTabControl.fMainTabsDictionary","href":"neTabControl.TneTabControl.fMainTabsDictionary.htm"}
,{"title":"fNumofDoMainChangeCalls","key":"neTabControl.TneTabControl.fNumofDoMainChangeCalls","href":"neTabControl.TneTabControl.fNumofDoMainChangeCalls.htm"}
,{"title":"fOnAfterAddItem","key":"neTabControl.TneTabControl.fOnAfterAddItem","href":"neTabControl.TneTabControl.fOnAfterAddItem.htm"}
,{"title":"fOnAfterAddSidebarControl","key":"neTabControl.TneTabControl.fOnAfterAddSidebarControl","href":"neTabControl.TneTabControl.fOnAfterAddSidebarControl.htm"}
,{"title":"fOnAfterCloseAllItems","key":"neTabControl.TneTabControl.fOnAfterCloseAllItems","href":"neTabControl.TneTabControl.fOnAfterCloseAllItems.htm"}
,{"title":"fOnAfterCloseOtherItems","key":"neTabControl.TneTabControl.fOnAfterCloseOtherItems","href":"neTabControl.TneTabControl.fOnAfterCloseOtherItems.htm"}
,{"title":"fOnAfterDeleteItem","key":"neTabControl.TneTabControl.fOnAfterDeleteItem","href":"neTabControl.TneTabControl.fOnAfterDeleteItem.htm"}
,{"title":"fOnAfterDeleteSidebarControl","key":"neTabControl.TneTabControl.fOnAfterDeleteSidebarControl","href":"neTabControl.TneTabControl.fOnAfterDeleteSidebarControl.htm"}
,{"title":"fOnBeforeAddItem","key":"neTabControl.TneTabControl.fOnBeforeAddItem","href":"neTabControl.TneTabControl.fOnBeforeAddItem.htm"}
,{"title":"fOnBeforeAddSidebarControl","key":"neTabControl.TneTabControl.fOnBeforeAddSidebarControl","href":"neTabControl.TneTabControl.fOnBeforeAddSidebarControl.htm"}
,{"title":"fOnBeforeCloseAllItems","key":"neTabControl.TneTabControl.fOnBeforeCloseAllItems","href":"neTabControl.TneTabControl.fOnBeforeCloseAllItems.htm"}
,{"title":"fOnBeforeCloseOtherItems","key":"neTabControl.TneTabControl.fOnBeforeCloseOtherItems","href":"neTabControl.TneTabControl.fOnBeforeCloseOtherItems.htm"}
,{"title":"fOnBeforeDeleteItem","key":"neTabControl.TneTabControl.fOnBeforeDeleteItem","href":"neTabControl.TneTabControl.fOnBeforeDeleteItem.htm"}
,{"title":"fOnBeforeDeleteSidebarControl","key":"neTabControl.TneTabControl.fOnBeforeDeleteSidebarControl","href":"neTabControl.TneTabControl.fOnBeforeDeleteSidebarControl.htm"}
,{"title":"fOnBeforePopupMenu","key":"neTabControl.TneTabControl.fOnBeforePopupMenu","href":"neTabControl.TneTabControl.fOnBeforePopupMenu.htm"}
,{"title":"fOnChange","key":"neTabControl.TneTabControl.fOnChange","href":"neTabControl.TneTabControl.fOnChange.htm"}
,{"title":"fOnCustomHint","key":"neTabControl.TneTabControl.fOnCustomHint","href":"neTabControl.TneTabControl.fOnCustomHint.htm"}
,{"title":"fPopup","key":"neTabControl.TneTabControl.fPopup","href":"neTabControl.TneTabControl.fPopup.htm"}
,{"title":"fRightLayout","key":"neTabControl.TneTabControl.fRightLayout","href":"neTabControl.TneTabControl.fRightLayout.htm"}
,{"title":"fRightSidebarControls","key":"neTabControl.TneTabControl.fRightSidebarControls","href":"neTabControl.TneTabControl.fRightSidebarControls.htm"}
,{"title":"fSubscriber","key":"neTabControl.TneTabControl.fSubscriber","href":"neTabControl.TneTabControl.fSubscriber.htm"}
,{"title":"fTabAnimation","key":"neTabControl.TneTabControl.fTabAnimation","href":"neTabControl.TneTabControl.fTabAnimation.htm"}
,{"title":"fTabAnimationDuration","key":"neTabControl.TneTabControl.fTabAnimationDuration","href":"neTabControl.TneTabControl.fTabAnimationDuration.htm"}
,{"title":"fTabAnimationInterpolation","key":"neTabControl.TneTabControl.fTabAnimationInterpolation","href":"neTabControl.TneTabControl.fTabAnimationInterpolation.htm"}
,{"title":"fTabAnimationType","key":"neTabControl.TneTabControl.fTabAnimationType","href":"neTabControl.TneTabControl.fTabAnimationType.htm"}
,{"title":"fTabBar","key":"neTabControl.TneTabControl.fTabBar","href":"neTabControl.TneTabControl.fTabBar.htm"}
,{"title":"fTabHeight","key":"neTabControl.TneTabControl.fTabHeight","href":"neTabControl.TneTabControl.fTabHeight.htm"}
,{"title":"fTabOrientation","key":"neTabControl.TneTabControl.fTabOrientation","href":"neTabControl.TneTabControl.fTabOrientation.htm"}
,{"title":"fTabPosition","key":"neTabControl.TneTabControl.fTabPosition","href":"neTabControl.TneTabControl.fTabPosition.htm"}
,{"title":"fTabsDictionary","key":"neTabControl.TneTabControl.fTabsDictionary","href":"neTabControl.TneTabControl.fTabsDictionary.htm"}
,{"title":"fTransitionType","key":"neTabControl.TneTabControl.fTransitionType","href":"neTabControl.TneTabControl.fTransitionType.htm"}
,{"title":"fVersion","key":"neTabControl.TneTabControl.fVersion","href":"neTabControl.TneTabControl.fVersion.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabControl_Enumerations","href":"neTabControl_Enumerations.htm","children":[{"title":"TneDoChangeType","key":"neTabControl.TneDoChangeType","href":"neTabControl.TneDoChangeType.htm"}
,{"title":"TneHintType","key":"neTabControl.TneHintType","href":"neTabControl.TneHintType.htm"}
,{"title":"TneSibebarControlPosition","key":"neTabControl.TneSibebarControlPosition","href":"neTabControl.TneSibebarControlPosition.htm"}
,{"title":"TneTabOrientation","key":"neTabControl.TneTabOrientation","href":"neTabControl.TneTabOrientation.htm"}
]}
,{"title":"Delegates","key":"neTabControl_Delegates","href":"neTabControl_Delegates.htm","children":[{"title":"TOnAfterAddItem","key":"neTabControl.TOnAfterAddItem","href":"neTabControl.TOnAfterAddItem.htm"}
,{"title":"TOnAfterAddSidebarControl","key":"neTabControl.TOnAfterAddSidebarControl","href":"neTabControl.TOnAfterAddSidebarControl.htm"}
,{"title":"TOnAfterCloseAllItems","key":"neTabControl.TOnAfterCloseAllItems","href":"neTabControl.TOnAfterCloseAllItems.htm"}
,{"title":"TOnAfterCloseOtherItems","key":"neTabControl.TOnAfterCloseOtherItems","href":"neTabControl.TOnAfterCloseOtherItems.htm"}
,{"title":"TOnAfterDeleteItem","key":"neTabControl.TOnAfterDeleteItem","href":"neTabControl.TOnAfterDeleteItem.htm"}
,{"title":"TOnAfterDeleteSidebarControl","key":"neTabControl.TOnAfterDeleteSidebarControl","href":"neTabControl.TOnAfterDeleteSidebarControl.htm"}
,{"title":"TOnBeforeAddItem","key":"neTabControl.TOnBeforeAddItem","href":"neTabControl.TOnBeforeAddItem.htm"}
,{"title":"TOnBeforeAddSibarControl","key":"neTabControl.TOnBeforeAddSibarControl","href":"neTabControl.TOnBeforeAddSibarControl.htm"}
,{"title":"TOnBeforeCloseAllItems","key":"neTabControl.TOnBeforeCloseAllItems","href":"neTabControl.TOnBeforeCloseAllItems.htm"}
,{"title":"TOnBeforeCloseOtherItems","key":"neTabControl.TOnBeforeCloseOtherItems","href":"neTabControl.TOnBeforeCloseOtherItems.htm"}
,{"title":"TOnBeforeDeleteItem","key":"neTabControl.TOnBeforeDeleteItem","href":"neTabControl.TOnBeforeDeleteItem.htm"}
,{"title":"TOnBeforeDeleteSidebarControl","key":"neTabControl.TOnBeforeDeleteSidebarControl","href":"neTabControl.TOnBeforeDeleteSidebarControl.htm"}
,{"title":"TOnBeforePopupMenu","key":"neTabControl.TOnBeforePopupMenu","href":"neTabControl.TOnBeforePopupMenu.htm"}
,{"title":"TOnCustomHint","key":"neTabControl.TOnCustomHint","href":"neTabControl.TOnCustomHint.htm"}
]}
,{"title":"Constants","key":"neTabControl_Constants","href":"neTabControl_Constants.htm","children":[{"title":"BugVersion","key":"neTabControl.BugVersion","href":"neTabControl.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabControl.MajorVersion","href":"neTabControl.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabControl.MinorVersion","href":"neTabControl.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabControl_Routines","href":"neTabControl_Routines.htm","children":[{"title":"GetTabControl(TClass)","key":"neTabControl.GetTabControl(TClass)","href":"neTabControl.GetTabControl.htm"}
,{"title":"Register","key":"neTabControl.Register","href":"neTabControl.Register.htm"}
]}
]}
,{"title":"neTabGeneralUtils","key":"neTabGeneralUtils","href":"neTabGeneralUtils.htm","children":[{"title":"Constants","key":"neTabGeneralUtils_Constants","href":"neTabGeneralUtils_Constants.htm","children":[{"title":"BugVersion","key":"neTabGeneralUtils.BugVersion","href":"neTabGeneralUtils.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabGeneralUtils.MajorVersion","href":"neTabGeneralUtils.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabGeneralUtils.MinorVersion","href":"neTabGeneralUtils.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabGeneralUtils_Routines","href":"neTabGeneralUtils_Routines.htm","children":[{"title":"FindParentForm(TFmxObject)","key":"neTabGeneralUtils.FindParentForm(TFmxObject)","href":"neTabGeneralUtils.FindParentForm.htm"}
,{"title":"LoadImageFromResources(string,TBitmap)","key":"neTabGeneralUtils.LoadImageFromResources(string,TBitmap@)","href":"neTabGeneralUtils.LoadImageFromResources.htm"}
]}
]}
,{"title":"neTabItem","key":"neTabItem","href":"neTabItem.htm","children":[{"title":"Classes","key":"neTabItem_Classes","href":"neTabItem_Classes.htm","children":[{"title":"TneCloseImageControl","key":"neTabItem.TneCloseImageControl","href":"neTabItem.TneCloseImageControl.htm","children":[{"title":"Constructors","key":"neTabItem.TneCloseImageControl_Constructors","href":"neTabItem.TneCloseImageControl_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabItem.TneCloseImageControl.Create(TComponent)","href":"neTabItem.TneCloseImageControl.Create.htm"}
,{"title":"Destroy","key":"neTabItem.TneCloseImageControl.Destroy","href":"neTabItem.TneCloseImageControl.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabItem.TneCloseImageControl_Properties","href":"neTabItem.TneCloseImageControl_Properties.htm","children":[{"title":"CloseImage","key":"neTabItem.TneCloseImageControl.CloseImage","href":"neTabItem.TneCloseImageControl.CloseImage.htm"}
]}
,{"title":"Methods","key":"neTabItem.TneCloseImageControl_Methods","href":"neTabItem.TneCloseImageControl_Methods.htm","children":[{"title":"DoMouseEnter","key":"neTabItem.TneCloseImageControl.DoMouseEnter","href":"neTabItem.TneCloseImageControl.DoMouseEnter.htm"}
,{"title":"DoMouseLeave","key":"neTabItem.TneCloseImageControl.DoMouseLeave","href":"neTabItem.TneCloseImageControl.DoMouseLeave.htm"}
,{"title":"GetCloseImage","key":"neTabItem.TneCloseImageControl.GetCloseImage","href":"neTabItem.TneCloseImageControl.GetCloseImage.htm"}
,{"title":"MouseDown(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneCloseImageControl.MouseDown(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseDown.htm"}
,{"title":"MouseUp(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneCloseImageControl.MouseUp(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneCloseImageControl.MouseUp.htm"}
,{"title":"NotifyTabItem(TIntAction)","key":"neTabItem.TneCloseImageControl.NotifyTabItem(TIntAction)","href":"neTabItem.TneCloseImageControl.NotifyTabItem.htm"}
,{"title":"SetCloseImage(TBitmap)","key":"neTabItem.TneCloseImageControl.SetCloseImage(TBitmap)","href":"neTabItem.TneCloseImageControl.SetCloseImage.htm"}
]}
,{"title":"Fields","key":"neTabItem.TneCloseImageControl_Fields","href":"neTabItem.TneCloseImageControl_Fields.htm","children":[{"title":"fProvider","key":"neTabItem.TneCloseImageControl.fProvider","href":"neTabItem.TneCloseImageControl.fProvider.htm"}
]}
]}
,{"title":"TneControl","key":"neTabItem.TneControl","href":"neTabItem.TneControl.htm","children":[{"title":"Properties","key":"neTabItem.TneControl_Properties","href":"neTabItem.TneControl_Properties.htm","children":[{"title":"InnerControl","key":"neTabItem.TneControl.InnerControl","href":"neTabItem.TneControl.InnerControl.htm"}
]}
,{"title":"Fields","key":"neTabItem.TneControl_Fields","href":"neTabItem.TneControl_Fields.htm","children":[{"title":"fControl","key":"neTabItem.TneControl.fControl","href":"neTabItem.TneControl.fControl.htm"}
]}
]}
,{"title":"TneTabItem","key":"neTabItem.TneTabItem","href":"neTabItem.TneTabItem.htm","children":[{"title":"Constructors","key":"neTabItem.TneTabItem_Constructors","href":"neTabItem.TneTabItem_Constructors.htm","children":[{"title":"Create(TComponent)","key":"neTabItem.TneTabItem.Create(TComponent)","href":"neTabItem.TneTabItem.Create.htm"}
,{"title":"Destroy","key":"neTabItem.TneTabItem.Destroy","href":"neTabItem.TneTabItem.Destroy.htm"}
]}
,{"title":"Properties","key":"neTabItem.TneTabItem_Properties","href":"neTabItem.TneTabItem_Properties.htm","children":[{"title":"CanClose","key":"neTabItem.TneTabItem.CanClose","href":"neTabItem.TneTabItem.CanClose.htm"}
,{"title":"Caption","key":"neTabItem.TneTabItem.Caption","href":"neTabItem.TneTabItem.Caption.htm"}
,{"title":"CaptionAlignment","key":"neTabItem.TneTabItem.CaptionAlignment","href":"neTabItem.TneTabItem.CaptionAlignment.htm"}
,{"title":"CloseAlignment","key":"neTabItem.TneTabItem.CloseAlignment","href":"neTabItem.TneTabItem.CloseAlignment.htm"}
,{"title":"CloseImageHover","key":"neTabItem.TneTabItem.CloseImageHover","href":"neTabItem.TneTabItem.CloseImageHover.htm"}
,{"title":"CloseImageNormal","key":"neTabItem.TneTabItem.CloseImageNormal","href":"neTabItem.TneTabItem.CloseImageNormal.htm"}
,{"title":"CloseImagePressed","key":"neTabItem.TneTabItem.CloseImagePressed","href":"neTabItem.TneTabItem.CloseImagePressed.htm"}
,{"title":"ControlAlignment","key":"neTabItem.TneTabItem.ControlAlignment","href":"neTabItem.TneTabItem.ControlAlignment.htm"}
,{"title":"ControlToShow","key":"neTabItem.TneTabItem.ControlToShow","href":"neTabItem.TneTabItem.ControlToShow.htm"}
,{"title":"HintInterval","key":"neTabItem.TneTabItem.HintInterval","href":"neTabItem.TneTabItem.HintInterval.htm"}
,{"title":"HintText","key":"neTabItem.TneTabItem.HintText","href":"neTabItem.TneTabItem.HintText.htm"}
,{"title":"MaxTabWidth","key":"neTabItem.TneTabItem.MaxTabWidth","href":"neTabItem.TneTabItem.MaxTabWidth.htm"}
,{"title":"MinTabWidth","key":"neTabItem.TneTabItem.MinTabWidth","href":"neTabItem.TneTabItem.MinTabWidth.htm"}
,{"title":"PopupMenuAfterDefault","key":"neTabItem.TneTabItem.PopupMenuAfterDefault","href":"neTabItem.TneTabItem.PopupMenuAfterDefault.htm"}
,{"title":"PopupMenuBeforeDefault","key":"neTabItem.TneTabItem.PopupMenuBeforeDefault","href":"neTabItem.TneTabItem.PopupMenuBeforeDefault.htm"}
,{"title":"Provider","key":"neTabItem.TneTabItem.Provider","href":"neTabItem.TneTabItem.Provider.htm"}
,{"title":"ShowControl","key":"neTabItem.TneTabItem.ShowControl","href":"neTabItem.TneTabItem.ShowControl.htm"}
,{"title":"ShowPopupMenu","key":"neTabItem.TneTabItem.ShowPopupMenu","href":"neTabItem.TneTabItem.ShowPopupMenu.htm"}
,{"title":"TabTag","key":"neTabItem.TneTabItem.TabTag","href":"neTabItem.TneTabItem.TabTag.htm"}
,{"title":"TabWidth","key":"neTabItem.TneTabItem.TabWidth","href":"neTabItem.TneTabItem.TabWidth.htm"}
]}
,{"title":"Methods","key":"neTabItem.TneTabItem_Methods","href":"neTabItem.TneTabItem_Methods.htm","children":[{"title":"ApplyStyle","key":"neTabItem.TneTabItem.ApplyStyle","href":"neTabItem.TneTabItem.ApplyStyle.htm"}
,{"title":"CloseMenuItem(TObject)","key":"neTabItem.TneTabItem.CloseMenuItem(TObject)","href":"neTabItem.TneTabItem.CloseMenuItem.htm"}
,{"title":"DoMouseLeave","key":"neTabItem.TneTabItem.DoMouseLeave","href":"neTabItem.TneTabItem.DoMouseLeave.htm"}
,{"title":"GetCloseImage(TCloseImagesType)","key":"neTabItem.TneTabItem.GetCloseImage(TCloseImagesType)","href":"neTabItem.TneTabItem.GetCloseImage.htm"}
,{"title":"GetTabWidth","key":"neTabItem.TneTabItem.GetTabWidth","href":"neTabItem.TneTabItem.GetTabWidth.htm"}
,{"title":"MouseClick(TMouseButton,TShiftState,Single,Single)","key":"neTabItem.TneTabItem.MouseClick(TMouseButton,TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseClick.htm"}
,{"title":"MouseMove(TShiftState,Single,Single)","key":"neTabItem.TneTabItem.MouseMove(TShiftState,Single,Single)","href":"neTabItem.TneTabItem.MouseMove.htm"}
,{"title":"NotifyToDeleteTab","key":"neTabItem.TneTabItem.NotifyToDeleteTab","href":"neTabItem.TneTabItem.NotifyToDeleteTab.htm"}
,{"title":"OnHintTimer(TObject)","key":"neTabItem.TneTabItem.OnHintTimer(TObject)","href":"neTabItem.TneTabItem.OnHintTimer.htm"}
,{"title":"OnInternalTimer(TObject)","key":"neTabItem.TneTabItem.OnInternalTimer(TObject)","href":"neTabItem.TneTabItem.OnInternalTimer.htm"}
,{"title":"RefreshControl","key":"neTabItem.TneTabItem.RefreshControl","href":"neTabItem.TneTabItem.RefreshControl.htm"}
,{"title":"SafeApplyStyle","key":"neTabItem.TneTabItem.SafeApplyStyle","href":"neTabItem.TneTabItem.SafeApplyStyle.htm"}
,{"title":"SetCanClose(Boolean)","key":"neTabItem.TneTabItem.SetCanClose(Boolean)","href":"neTabItem.TneTabItem.SetCanClose.htm"}
,{"title":"SetCaption(TLabel)","key":"neTabItem.TneTabItem.SetCaption(TLabel)","href":"neTabItem.TneTabItem.SetCaption.htm"}
,{"title":"SetCaptionAlignment(TAlignLayout)","key":"neTabItem.TneTabItem.SetCaptionAlignment(TAlignLayout)","href":"neTabItem.TneTabItem.SetCaptionAlignment.htm"}
,{"title":"SetCloseAlignment(TalignLayout)","key":"neTabItem.TneTabItem.SetCloseAlignment(TalignLayout)","href":"neTabItem.TneTabItem.SetCloseAlignment.htm"}
,{"title":"SetCloseImage(TCloseImagesType,TBitmap)","key":"neTabItem.TneTabItem.SetCloseImage(TCloseImagesType,TBitmap)","href":"neTabItem.TneTabItem.SetCloseImage.htm"}
,{"title":"SetControlAlignment(TAlignLayout)","key":"neTabItem.TneTabItem.SetControlAlignment(TAlignLayout)","href":"neTabItem.TneTabItem.SetControlAlignment.htm"}
,{"title":"SetControlToShow(TControl)","key":"neTabItem.TneTabItem.SetControlToShow(TControl)","href":"neTabItem.TneTabItem.SetControlToShow.htm"}
,{"title":"SetMaxTabWidth(single)","key":"neTabItem.TneTabItem.SetMaxTabWidth(single)","href":"neTabItem.TneTabItem.SetMaxTabWidth.htm"}
,{"title":"SetMinTabWidth(single)","key":"neTabItem.TneTabItem.SetMinTabWidth(single)","href":"neTabItem.TneTabItem.SetMinTabWidth.htm"}
,{"title":"SetShowControl(Boolean)","key":"neTabItem.TneTabItem.SetShowControl(Boolean)","href":"neTabItem.TneTabItem.SetShowControl.htm"}
,{"title":"SetTabWidth(single)","key":"neTabItem.TneTabItem.SetTabWidth(single)","href":"neTabItem.TneTabItem.SetTabWidth.htm"}
,{"title":"SetWidth(Single)","key":"neTabItem.TneTabItem.SetWidth(Single)","href":"neTabItem.TneTabItem.SetWidth.htm"}
,{"title":"ShowFullPopupMenu(TObject,Single,Single)","key":"neTabItem.TneTabItem.ShowFullPopupMenu(TObject,Single,Single)","href":"neTabItem.TneTabItem.ShowFullPopupMenu.htm"}
,{"title":"UpdateFromProvider(INotification)","key":"neTabItem.TneTabItem.UpdateFromProvider(INotification)","href":"neTabItem.TneTabItem.UpdateFromProvider.htm"}
]}
,{"title":"Fields","key":"neTabItem.TneTabItem_Fields","href":"neTabItem.TneTabItem_Fields.htm","children":[{"title":"fCanClose","key":"neTabItem.TneTabItem.fCanClose","href":"neTabItem.TneTabItem.fCanClose.htm"}
,{"title":"fCaption","key":"neTabItem.TneTabItem.fCaption","href":"neTabItem.TneTabItem.fCaption.htm"}
,{"title":"fCaptionAlignment","key":"neTabItem.TneTabItem.fCaptionAlignment","href":"neTabItem.TneTabItem.fCaptionAlignment.htm"}
,{"title":"fCloseAlignment","key":"neTabItem.TneTabItem.fCloseAlignment","href":"neTabItem.TneTabItem.fCloseAlignment.htm"}
,{"title":"fCloseImages","key":"neTabItem.TneTabItem.fCloseImages","href":"neTabItem.TneTabItem.fCloseImages.htm"}
,{"title":"fCloseImageToShow","key":"neTabItem.TneTabItem.fCloseImageToShow","href":"neTabItem.TneTabItem.fCloseImageToShow.htm"}
,{"title":"fControlAlignment","key":"neTabItem.TneTabItem.fControlAlignment","href":"neTabItem.TneTabItem.fControlAlignment.htm"}
,{"title":"fControlToShow","key":"neTabItem.TneTabItem.fControlToShow","href":"neTabItem.TneTabItem.fControlToShow.htm"}
,{"title":"fHintInterval","key":"neTabItem.TneTabItem.fHintInterval","href":"neTabItem.TneTabItem.fHintInterval.htm"}
,{"title":"fHintText","key":"neTabItem.TneTabItem.fHintText","href":"neTabItem.TneTabItem.fHintText.htm"}
,{"title":"fHintTimer","key":"neTabItem.TneTabItem.fHintTimer","href":"neTabItem.TneTabItem.fHintTimer.htm"}
,{"title":"fInternalTimer","key":"neTabItem.TneTabItem.fInternalTimer","href":"neTabItem.TneTabItem.fInternalTimer.htm"}
,{"title":"fLastMousePoint","key":"neTabItem.TneTabItem.fLastMousePoint","href":"neTabItem.TneTabItem.fLastMousePoint.htm"}
,{"title":"fMaxTabWidth","key":"neTabItem.TneTabItem.fMaxTabWidth","href":"neTabItem.TneTabItem.fMaxTabWidth.htm"}
,{"title":"fMinTabWidth","key":"neTabItem.TneTabItem.fMinTabWidth","href":"neTabItem.TneTabItem.fMinTabWidth.htm"}
,{"title":"fMouseState","key":"neTabItem.TneTabItem.fMouseState","href":"neTabItem.TneTabItem.fMouseState.htm"}
,{"title":"fPopupMenuAfterDefault","key":"neTabItem.TneTabItem.fPopupMenuAfterDefault","href":"neTabItem.TneTabItem.fPopupMenuAfterDefault.htm"}
,{"title":"fPopupMenuBeforeDefault","key":"neTabItem.TneTabItem.fPopupMenuBeforeDefault","href":"neTabItem.TneTabItem.fPopupMenuBeforeDefault.htm"}
,{"title":"fProvider","key":"neTabItem.TneTabItem.fProvider","href":"neTabItem.TneTabItem.fProvider.htm"}
,{"title":"fRefreshCloseImage","key":"neTabItem.TneTabItem.fRefreshCloseImage","href":"neTabItem.TneTabItem.fRefreshCloseImage.htm"}
,{"title":"fShowControl","key":"neTabItem.TneTabItem.fShowControl","href":"neTabItem.TneTabItem.fShowControl.htm"}
,{"title":"fShowPopupMenu","key":"neTabItem.TneTabItem.fShowPopupMenu","href":"neTabItem.TneTabItem.fShowPopupMenu.htm"}
,{"title":"fSubscriber","key":"neTabItem.TneTabItem.fSubscriber","href":"neTabItem.TneTabItem.fSubscriber.htm"}
,{"title":"fTabTag","key":"neTabItem.TneTabItem.fTabTag","href":"neTabItem.TneTabItem.fTabTag.htm"}
,{"title":"fTabWidth","key":"neTabItem.TneTabItem.fTabWidth","href":"neTabItem.TneTabItem.fTabWidth.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabItem_Enumerations","href":"neTabItem_Enumerations.htm","children":[{"title":"TCloseImagesType","key":"neTabItem.TCloseImagesType","href":"neTabItem.TCloseImagesType.htm"}
,{"title":"TMouseState","key":"neTabItem.TMouseState","href":"neTabItem.TMouseState.htm"}
]}
,{"title":"Constants","key":"neTabItem_Constants","href":"neTabItem_Constants.htm","children":[{"title":"BugVersion","key":"neTabItem.BugVersion","href":"neTabItem.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabItem.MajorVersion","href":"neTabItem.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabItem.MinorVersion","href":"neTabItem.MinorVersion.htm"}
]}
,{"title":"Routines","key":"neTabItem_Routines","href":"neTabItem_Routines.htm","children":[{"title":"register","key":"neTabItem.register","href":"neTabItem.register.htm"}
]}
]}
,{"title":"neTabTypes","key":"neTabTypes","href":"neTabTypes.htm","children":[{"title":"Classes","key":"neTabTypes_Classes","href":"neTabTypes_Classes.htm","children":[{"title":"THistoryClass","key":"neTabTypes.THistoryClass","href":"neTabTypes.THistoryClass.htm","children":[{"title":"Constructors","key":"neTabTypes.THistoryClass_Constructors","href":"neTabTypes.THistoryClass_Constructors.htm","children":[{"title":"Create","key":"neTabTypes.THistoryClass.Create","href":"neTabTypes.THistoryClass.Create.htm"}
,{"title":"Destroy","key":"neTabTypes.THistoryClass.Destroy","href":"neTabTypes.THistoryClass.Destroy.htm"}
]}
,{"title":"Methods","key":"neTabTypes.THistoryClass_Methods","href":"neTabTypes.THistoryClass_Methods.htm","children":[{"title":"AddHistory(string)","key":"neTabTypes.THistoryClass.AddHistory(string)","href":"neTabTypes.THistoryClass.AddHistory.htm"}
,{"title":"DeleteHistory(string)","key":"neTabTypes.THistoryClass.DeleteHistory(string)","href":"neTabTypes.THistoryClass.DeleteHistory.htm"}
,{"title":"GetLastEntry","key":"neTabTypes.THistoryClass.GetLastEntry","href":"neTabTypes.THistoryClass.GetLastEntry.htm"}
]}
,{"title":"Fields","key":"neTabTypes.THistoryClass_Fields","href":"neTabTypes.THistoryClass_Fields.htm","children":[{"title":"fHistoryList","key":"neTabTypes.THistoryClass.fHistoryList","href":"neTabTypes.THistoryClass.fHistoryList.htm"}
]}
]}
,{"title":"TneHintTimer","key":"neTabTypes.TneHintTimer","href":"neTabTypes.TneHintTimer.htm","children":[{"title":"Fields","key":"neTabTypes.TneHintTimer_Fields","href":"neTabTypes.TneHintTimer_Fields.htm","children":[{"title":"MousePoint","key":"neTabTypes.TneHintTimer.MousePoint","href":"neTabTypes.TneHintTimer.MousePoint.htm"}
]}
]}
,{"title":"TneNotificationClass","key":"neTabTypes.TneNotificationClass","href":"neTabTypes.TneNotificationClass.htm","children":[{"title":"Properties","key":"neTabTypes.TneNotificationClass_Properties","href":"neTabTypes.TneNotificationClass_Properties.htm","children":[{"title":"Action","key":"neTabTypes.TneNotificationClass.Action","href":"neTabTypes.TneNotificationClass.Action.htm"}
,{"title":"Point","key":"neTabTypes.TneNotificationClass.Point","href":"neTabTypes.TneNotificationClass.Point.htm"}
,{"title":"PopupAfter","key":"neTabTypes.TneNotificationClass.PopupAfter","href":"neTabTypes.TneNotificationClass.PopupAfter.htm"}
,{"title":"PopupBefore","key":"neTabTypes.TneNotificationClass.PopupBefore","href":"neTabTypes.TneNotificationClass.PopupBefore.htm"}
,{"title":"PopupDefault","key":"neTabTypes.TneNotificationClass.PopupDefault","href":"neTabTypes.TneNotificationClass.PopupDefault.htm"}
,{"title":"Sender","key":"neTabTypes.TneNotificationClass.Sender","href":"neTabTypes.TneNotificationClass.Sender.htm"}
,{"title":"Value","key":"neTabTypes.TneNotificationClass.Value","href":"neTabTypes.TneNotificationClass.Value.htm"}
,{"title":"ValueInt","key":"neTabTypes.TneNotificationClass.ValueInt","href":"neTabTypes.TneNotificationClass.ValueInt.htm"}
]}
,{"title":"Fields","key":"neTabTypes.TneNotificationClass_Fields","href":"neTabTypes.TneNotificationClass_Fields.htm","children":[{"title":"fActions","key":"neTabTypes.TneNotificationClass.fActions","href":"neTabTypes.TneNotificationClass.fActions.htm"}
,{"title":"fPoint","key":"neTabTypes.TneNotificationClass.fPoint","href":"neTabTypes.TneNotificationClass.fPoint.htm"}
,{"title":"fPopupAfter","key":"neTabTypes.TneNotificationClass.fPopupAfter","href":"neTabTypes.TneNotificationClass.fPopupAfter.htm"}
,{"title":"fPopupBefore","key":"neTabTypes.TneNotificationClass.fPopupBefore","href":"neTabTypes.TneNotificationClass.fPopupBefore.htm"}
,{"title":"fPopupDefault","key":"neTabTypes.TneNotificationClass.fPopupDefault","href":"neTabTypes.TneNotificationClass.fPopupDefault.htm"}
,{"title":"fSender","key":"neTabTypes.TneNotificationClass.fSender","href":"neTabTypes.TneNotificationClass.fSender.htm"}
,{"title":"fValue","key":"neTabTypes.TneNotificationClass.fValue","href":"neTabTypes.TneNotificationClass.fValue.htm"}
,{"title":"fValueInt","key":"neTabTypes.TneNotificationClass.fValueInt","href":"neTabTypes.TneNotificationClass.fValueInt.htm"}
]}
]}
,{"title":"TneTimer","key":"neTabTypes.TneTimer","href":"neTabTypes.TneTimer.htm","children":[{"title":"Fields","key":"neTabTypes.TneTimer_Fields","href":"neTabTypes.TneTimer_Fields.htm","children":[{"title":"Action","key":"neTabTypes.TneTimer.Action","href":"neTabTypes.TneTimer.Action.htm"}
,{"title":"Value","key":"neTabTypes.TneTimer.Value","href":"neTabTypes.TneTimer.Value.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"neTabTypes_Enumerations","href":"neTabTypes_Enumerations.htm","children":[{"title":"TExportElement","key":"neTabTypes.TExportElement","href":"neTabTypes.TExportElement.htm"}
,{"title":"TShowTabAnimation","key":"neTabTypes.TShowTabAnimation","href":"neTabTypes.TShowTabAnimation.htm"}
]}
,{"title":"Types","key":"neTabTypes_Types","href":"neTabTypes_Types.htm","children":[{"title":"TExportElements","key":"neTabTypes.TExportElements","href":"neTabTypes.TExportElements.htm"}
,{"title":"TSetOfStrings","key":"neTabTypes.TSetOfStrings","href":"neTabTypes.TSetOfStrings.htm"}
]}
,{"title":"Constants","key":"neTabTypes_Constants","href":"neTabTypes_Constants.htm","children":[{"title":"BugVersion","key":"neTabTypes.BugVersion","href":"neTabTypes.BugVersion.htm"}
,{"title":"MajorVersion","key":"neTabTypes.MajorVersion","href":"neTabTypes.MajorVersion.htm"}
,{"title":"MinorVersion","key":"neTabTypes.MinorVersion","href":"neTabTypes.MinorVersion.htm"}
,{"title":"SCloseAllTabs","key":"neTabTypes.SCloseAllTabs","href":"neTabTypes.SCloseAllTabs.htm"}
,{"title":"SCloseOtherTabs","key":"neTabTypes.SCloseOtherTabs","href":"neTabTypes.SCloseOtherTabs.htm"}
,{"title":"SCloseTab","key":"neTabTypes.SCloseTab","href":"neTabTypes.SCloseTab.htm"}
]}
]}
]}
]